// i18n strings for the DOM UI shell (keys ui.*). OWNER: src/ui.
// Imported for its side effect by shell.ts. Finnish terms follow research/glossary-fi.json
// (freeze-frame = pysäytyskuva, education = opetus, orbit = kiertokamera).
import { registerStrings } from '../i18n.ts';

registerStrings({
  en: {
    // ── brand / top bar ───────────────────────────────────────────────
    'ui.title': 'Starship',
    'ui.flight': 'Flight 14',
    'ui.badge': 'FREEZE-FRAME · T+{t} s',
    'ui.badge.tip': 'The scene is frozen at {t} seconds after liftoff',
    'ui.fps': '{fps} fps',
    // ── camera ────────────────────────────────────────────────────────
    'ui.camera': 'Camera',
    'ui.mode.orbit': 'Orbit',
    'ui.mode.photo': 'Photo',
    'ui.mode.walk': 'Walk',
    'ui.mode.fly': 'Fly',
    'ui.mode.orbit.tip': 'Orbit around the pad (1)',
    'ui.mode.photo.tip': 'Return to the photographer’s viewpoint (2)',
    'ui.mode.walk.tip': 'Walk on the ground, first person (3)',
    'ui.mode.fly.tip': 'Free-fly camera (4)',
    // ── lighting ──────────────────────────────────────────────────────
    'ui.lighting': 'Lighting',
    'ui.lighting.tip': 'Lighting preset (L cycles)',
    'ui.preset.photo': 'Photo · sunrise',
    'ui.preset.noon': 'Noon',
    'ui.preset.night': 'Night launch',
    'ui.preset.thermal': 'Thermal',
    'ui.preset.clay': 'Clay',
    'ui.preset.photo.s': 'Photo',
    'ui.preset.noon.s': 'Noon',
    'ui.preset.night.s': 'Night',
    'ui.preset.thermal.s': 'Thermal',
    'ui.preset.clay.s': 'Clay',
    'ui.preset.photo.d': 'Golden light matching the reference',
    'ui.preset.noon.d': 'High sun, harsh and neutral',
    'ui.preset.night.d': 'The plume lights the whole pad',
    'ui.preset.thermal.d': 'False-colour temperature',
    'ui.preset.clay.d': 'Plain grey shapes, lighting only',
    // ── quality ───────────────────────────────────────────────────────
    'ui.quality': 'Quality',
    'ui.quality.tip': 'Rendering quality',
    'ui.quality.auto': 'Auto',
    'ui.quality.low': 'Low',
    'ui.quality.medium': 'Medium',
    'ui.quality.high': 'High',
    'ui.quality.ultra': 'Ultra',
    'ui.quality.auto.d': 'Adapts to hold 60 fps',
    'ui.quality.low.d': 'Integrated graphics, battery',
    'ui.quality.medium.d': 'Balanced',
    'ui.quality.high.d': 'Default for a modern iGPU or better',
    'ui.quality.ultra.d': 'Dedicated GPU, sharpest clouds',
    'ui.quality.autoNow': 'Auto · {q}',
    // ── toggles / actions ─────────────────────────────────────────────
    'ui.drift': 'Slow drift',
    'ui.drift.tip': 'Let clouds and plume drift slowly (off = perfectly frozen)',
    'ui.edu': 'Education',
    'ui.edu.tip': 'Show labelled hotspots and explainers (E)',
    'ui.lang': 'Language',
    'ui.export': 'Export still',
    'ui.export.tip': 'Save the current view as a PNG',
    'ui.lens': 'Lens',
    'ui.lens.tip': 'Lens and tilt-shift controls',
    'ui.menu': 'Menu',
    'ui.menu.tip': 'More controls',
    'ui.help': 'Help',
    'ui.help.tip': 'Keyboard shortcuts (?)',
    'ui.about': 'About',
    'ui.about.tip': 'About and credits',
    'ui.hide': 'Hide UI',
    'ui.hide.tip': 'Hide all interface (H)',
    'ui.unhide': 'Show interface',
    'ui.on': 'On',
    'ui.off': 'Off',
    'ui.close': 'Close',
    // ── lens panel ────────────────────────────────────────────────────
    'ui.lens.title': 'Lens',
    'ui.lens.fov': 'Field of view',
    'ui.lens.dolly': 'Dolly zoom',
    'ui.lens.dolly.d': 'Move the camera as you change FOV so the subject keeps its size',
    'ui.lens.roll': 'Roll',
    'ui.lens.ts': 'Tilt-shift',
    'ui.lens.ts.d': 'Miniature effect: only a band of the frame stays sharp',
    'ui.lens.focus': 'Focus position',
    'ui.lens.band': 'Sharp band',
    'ui.lens.blur': 'Blur',
    'ui.lens.reset': 'Reset lens',
    // ── toasts ────────────────────────────────────────────────────────
    'ui.toast.mode': 'Camera: {name}',
    'ui.toast.preset': 'Lighting: {name}',
    'ui.toast.quality': 'Quality: {name}',
    'ui.toast.edu.on': 'Education mode on',
    'ui.toast.edu.off': 'Education mode off',
    'ui.toast.drift.on': 'Slow drift on',
    'ui.toast.drift.off': 'Frozen',
    'ui.toast.hidden': 'Interface hidden · press H to show it again',
    'ui.toast.reset': 'View and lens reset',
    'ui.toast.exporting': 'Saving still…',
    // ── walk / fly overlay ────────────────────────────────────────────
    'ui.walk.prompt': 'Click to look around · Esc to release',
    'ui.walk.hint': '{move} move · {run} run · {crouch} crouch · {jump} jump · {esc} release',
    'ui.fly.hint': 'Drag to look · {move} move · {qe} down / up · {run} boost',
    'ui.walk.hint.touch': 'Left stick to move · drag to look · double-tap to jump',
    'ui.fly.hint.touch': 'Left stick to move · drag to look',
    'ui.toast.hidden.touch': 'Interface hidden · tap the eye to show it again',
    'ui.walk.crosshair': 'Crosshair',
    // ── help ──────────────────────────────────────────────────────────
    'ui.help.title': 'Keyboard shortcuts',
    'ui.help.g.view': 'View',
    'ui.help.g.lens': 'Lens',
    'ui.help.g.move': 'Move (walk and fly)',
    'ui.help.g.ui': 'Interface',
    'ui.help.k.modes': 'Orbit, Photo, Walk, Fly',
    'ui.help.k.preset': 'Cycle lighting preset',
    'ui.help.k.reset': 'Reset camera and lens',
    'ui.help.k.fov': 'Narrower / wider field of view',
    'ui.help.k.roll': 'Roll left / right',
    'ui.help.k.move': 'Move forward, left, back, right',
    'ui.help.k.run': 'Run (walk) / boost (fly)',
    'ui.help.k.crouch': 'Crouch (walk) / descend (fly)',
    'ui.help.k.hyper': 'Hyper walk, 40 m/s (toggle, walk)',
    'ui.help.k.jump': 'Jump (walk) / rise (fly)',
    'ui.help.k.qe': 'Descend / ascend (fly only)',
    'ui.help.k.edu': 'Education mode (not in fly mode)',
    'ui.help.k.hide': 'Hide or show all interface',
    'ui.help.k.help': 'This help',
    'ui.help.k.esc': 'Release the mouse, close panels',
    'ui.help.note': 'Tip: drag to orbit, scroll to zoom, right-drag to pan. In walk mode click the view to capture the mouse; in fly mode the scroll wheel sets the speed.',
    // ── about ─────────────────────────────────────────────────────────
    'ui.about.title': 'About this scene',
    'ui.about.p1': 'A frozen moment of Starship Flight 14: Super Heavy B21 and Ship S41 (Block 3) leaving Starbase Pad 2 at about T+7.2 s, 28 September 2026, 07:48 CDT.',
    'ui.about.p2': 'Every model, cloud and flame is built from scratch from published research: dimensions, engine data, weather and geography. Estimates are marked as such in the education cards.',
    'ui.about.p3': 'The reference photograph was posted on X on 2026-09-28 and is not redistributed here; it was used only to calibrate the camera and the look.',
    'ui.about.p4': 'Map data © OpenStreetMap contributors, available under the Open Database Licence (ODbL).',
    'ui.about.p5': 'This is an independent educational project. It is not affiliated with or endorsed by SpaceX.',
    // ── loading ───────────────────────────────────────────────────────
    'ui.loading.title': 'Loading',
    'ui.loading.models': 'Loading models',
    'ui.loading.textures': 'Loading textures',
    'ui.loading.clouds': 'Baking clouds',
    'ui.loading.shaders': 'Compiling shaders',
    'ui.loading.pad': 'Building the pad',
    'ui.loading.frame': 'Rendering the first frame',
    'ui.loading.ready': 'Ready',
    'ui.loading.tag': 'Freeze-frame · T+{t} s',
  },
  fi: {
    'ui.title': 'Starship',
    'ui.flight': 'Lento 14',
    'ui.badge': 'PYSÄYTYSKUVA · T+{t} s',
    'ui.badge.tip': 'Kohtaus on pysäytetty {t} sekuntia nousun jälkeen',
    'ui.fps': '{fps} kuvaa/s',

    'ui.camera': 'Kamera',
    'ui.mode.orbit': 'Kierto',
    'ui.mode.photo': 'Valokuva',
    'ui.mode.walk': 'Kävely',
    'ui.mode.fly': 'Lento',
    'ui.mode.orbit.tip': 'Kierrä laukaisualustaa (1)',
    'ui.mode.photo.tip': 'Palaa valokuvaajan näkökulmaan (2)',
    'ui.mode.walk.tip': 'Kävele maassa ensimmäisessä persoonassa (3)',
    'ui.mode.fly.tip': 'Vapaa lentokamera (4)',

    'ui.lighting': 'Valaistus',
    'ui.lighting.tip': 'Valaistuksen esiasetus (L vaihtaa)',
    'ui.preset.photo': 'Valokuva · auringonnousu',
    'ui.preset.noon': 'Keskipäivä',
    'ui.preset.night': 'Yölaukaisu',
    'ui.preset.thermal': 'Lämpökuva',
    'ui.preset.clay': 'Savimalli',
    'ui.preset.photo.s': 'Valokuva',
    'ui.preset.noon.s': 'Keskipäivä',
    'ui.preset.night.s': 'Yö',
    'ui.preset.thermal.s': 'Lämpö',
    'ui.preset.clay.s': 'Savi',
    'ui.preset.photo.d': 'Kultainen valo, kuten alkuperäisessä kuvassa',
    'ui.preset.noon.d': 'Korkealla oleva aurinko, kova ja neutraali',
    'ui.preset.night.d': 'Suihku valaisee koko alustan',
    'ui.preset.thermal.d': 'Lämpötila valheväreinä',
    'ui.preset.clay.d': 'Harmaat muodot, vain valaistus',

    'ui.quality': 'Laatu',
    'ui.quality.tip': 'Piirtolaatu',
    'ui.quality.auto': 'Auto',
    'ui.quality.low': 'Matala',
    'ui.quality.medium': 'Keskitaso',
    'ui.quality.high': 'Korkea',
    'ui.quality.ultra': 'Ultra',
    'ui.quality.auto.d': 'Mukautuu pitämään 60 kuvaa/s',
    'ui.quality.low.d': 'Integroitu näytönohjain, akku',
    'ui.quality.medium.d': 'Tasapainoinen',
    'ui.quality.high.d': 'Oletus: nykyaikainen integroitu tai parempi näytönohjain',
    'ui.quality.ultra.d': 'Erillinen näytönohjain, terävimmät pilvet',
    'ui.quality.autoNow': 'Auto · {q}',

    'ui.drift': 'Hidas liike',
    'ui.drift.tip': 'Anna pilvien ja suihkun lipua hitaasti (pois = täysin pysähtynyt)',
    'ui.edu': 'Opetus',
    'ui.edu.tip': 'Näytä merkityt kohteet ja selitykset (E)',
    'ui.lang': 'Kieli',
    'ui.export': 'Tallenna kuva',
    'ui.export.tip': 'Tallenna nykyinen näkymä PNG-kuvana',
    'ui.lens': 'Linssi',
    'ui.lens.tip': 'Linssin ja tilt-shift-tehosteen säädöt',
    'ui.menu': 'Valikko',
    'ui.menu.tip': 'Lisää säätimiä',
    'ui.help': 'Ohje',
    'ui.help.tip': 'Pikanäppäimet (?)',
    'ui.about': 'Tietoja',
    'ui.about.tip': 'Tietoja, tekijät ja lähteet',
    'ui.hide': 'Piilota käyttöliittymä',
    'ui.hide.tip': 'Piilota kaikki käyttöliittymä (H)',
    'ui.unhide': 'Näytä käyttöliittymä',
    'ui.on': 'Päällä',
    'ui.off': 'Pois',
    'ui.close': 'Sulje',

    'ui.lens.title': 'Linssi',
    'ui.lens.fov': 'Näkökenttä',
    'ui.lens.dolly': 'Dolly-zoom',
    'ui.lens.dolly.d': 'Liikuta kameraa näkökenttää säätäessä, jolloin kohde säilyttää kokonsa',
    'ui.lens.roll': 'Kallistus',
    'ui.lens.ts': 'Tilt-shift',
    'ui.lens.ts.d': 'Pienoismalliefekti: vain kuvan kaista pysyy terävänä',
    'ui.lens.focus': 'Tarkennuskohta',
    'ui.lens.band': 'Terävä kaista',
    'ui.lens.blur': 'Sumennus',
    'ui.lens.reset': 'Palauta linssi',

    'ui.toast.mode': 'Kamera: {name}',
    'ui.toast.preset': 'Valaistus: {name}',
    'ui.toast.quality': 'Laatu: {name}',
    'ui.toast.edu.on': 'Opetustila päällä',
    'ui.toast.edu.off': 'Opetustila pois',
    'ui.toast.drift.on': 'Hidas liike päällä',
    'ui.toast.drift.off': 'Pysäytetty',
    'ui.toast.hidden': 'Käyttöliittymä piilotettu · H tuo sen takaisin',
    'ui.toast.reset': 'Näkymä ja linssi palautettu',
    'ui.toast.exporting': 'Tallennetaan kuvaa…',

    'ui.walk.prompt': 'Klikkaa katsoaksesi ympärillesi · Esc vapauttaa hiiren',
    'ui.walk.hint': '{move} liiku · {run} juokse · {crouch} kyyristy · {jump} hyppää · {esc} vapauta',
    'ui.fly.hint': 'Raahaa katsoaksesi · {move} liiku · {qe} alas / ylös · {run} vauhti',
    'ui.walk.hint.touch': 'Vasen sauva liikuttaa · raahaa katsoaksesi · kaksoisnapautus hyppää',
    'ui.fly.hint.touch': 'Vasen sauva liikuttaa · raahaa katsoaksesi',
    'ui.toast.hidden.touch': 'Käyttöliittymä piilotettu · napauta silmää tuodaksesi sen takaisin',
    'ui.walk.crosshair': 'Tähtäin',

    'ui.help.title': 'Pikanäppäimet',
    'ui.help.g.view': 'Näkymä',
    'ui.help.g.lens': 'Linssi',
    'ui.help.g.move': 'Liikkuminen (kävely ja lento)',
    'ui.help.g.ui': 'Käyttöliittymä',
    'ui.help.k.modes': 'Kierto, Valokuva, Kävely, Lento',
    'ui.help.k.preset': 'Vaihda valaistuksen esiasetusta',
    'ui.help.k.reset': 'Palauta kamera ja linssi',
    'ui.help.k.fov': 'Kapeampi / laajempi näkökenttä',
    'ui.help.k.roll': 'Kallista vasemmalle / oikealle',
    'ui.help.k.move': 'Liiku eteen, vasemmalle, taakse, oikealle',
    'ui.help.k.run': 'Juokse (kävely) / vauhti (lento)',
    'ui.help.k.crouch': 'Kyyristy (kävely) / laskeudu (lento)',
    'ui.help.k.hyper': 'Hyperkävely 40 m/s (kytkin, kävely)',
    'ui.help.k.jump': 'Hyppää (kävely) / nouse (lento)',
    'ui.help.k.qe': 'Laskeudu / nouse (vain lento)',
    'ui.help.k.edu': 'Opetustila (ei lentotilassa)',
    'ui.help.k.hide': 'Piilota tai näytä koko käyttöliittymä',
    'ui.help.k.help': 'Tämä ohje',
    'ui.help.k.esc': 'Vapauta hiiri, sulje paneelit',
    'ui.help.note': 'Vinkki: raahaa kiertääksesi, vieritä zoomataksesi, siirrä näkymää oikealla painikkeella. Kävelytilassa klikkaa näkymää kaapataksesi hiiren; lentotilassa vierityspyörä säätää nopeutta.',

    'ui.about.title': 'Tietoja tästä kohtauksesta',
    'ui.about.p1': 'Pysäytetty hetki Starshipin lennolta 14: Super Heavy B21 ja Starship S41 (Block 3) nousevat Starbasen laukaisualustalta 2 hetkellä noin T+7,2 s, 28.9.2026 kello 07.48 (CDT).',
    'ui.about.p2': 'Jokainen malli, pilvi ja liekki on rakennettu alusta alkaen julkaistun tutkimuksen pohjalta: mitat, moottoritiedot, sää ja maasto. Arviot on merkitty opetuskorteissa arvioiksi.',
    'ui.about.p3': 'Vertailukuva julkaistiin X:ssä 28.9.2026, eikä sitä jaeta tässä. Sitä käytettiin vain kameran ja ulkoasun kalibrointiin.',
    'ui.about.p4': 'Karttatiedot © OpenStreetMapin tekijät, käytettävissä Open Database License (ODbL) -lisenssillä.',
    'ui.about.p5': 'Tämä on riippumaton opetushanke. Se ei liity SpaceXiin, eikä SpaceX ole hyväksynyt sitä.',

    'ui.loading.title': 'Ladataan',
    'ui.loading.models': 'Ladataan malleja',
    'ui.loading.textures': 'Ladataan tekstuureja',
    'ui.loading.clouds': 'Esilasketaan pilviä',
    'ui.loading.shaders': 'Käännetään varjostimia',
    'ui.loading.pad': 'Rakennetaan laukaisualustaa',
    'ui.loading.frame': 'Piirretään ensimmäistä kuvaa',
    'ui.loading.ready': 'Valmis',
    'ui.loading.tag': 'Pysäytyskuva · T+{t} s',
  },
});
