// English strings for the educational mode. {name} placeholders are filled LIVE from the spec and
// the liftoff model by src/edu/vars.ts (so every number in the prose follows specs/starship.json).
// Hotspot bodies are 60-120 words (checked by tests/physics.test.ts). Explainer paragraphs are
// separated by a blank line. Finnish counterpart: content.fi.ts (same keys).

export const en: Record<string, string> = {
  // ── shell ────────────────────────────────────────────────────────────────────────────────
  'edu.title': 'Educational mode',
  'edu.panel.title': 'Physics of this moment',
  'edu.panel.aria': 'Physics of this moment: numbers, charts, explainers and sources',
  'edu.tab.moment': 'Moment',
  'edu.tab.explain': 'Explainers',
  'edu.tab.sources': 'Sources',
  'edu.collapse': 'Hide panel',
  'edu.expand': 'Show panel',
  'edu.close': 'Close',
  'edu.exit': 'Leave educational mode',
  'edu.pill': 'Physics of this moment',
  'edu.markers.aria': 'Hotspots. Choose one to read about it.',
  'edu.marker.open': 'Open the card for {title}',
  'edu.cat.vehicle': 'Vehicle',
  'edu.cat.pad': 'Launch site',
  'edu.cat.fx': 'Plume and clouds',
  'edu.cat.physics': 'Physics',
  'edu.badge.src': 'sourced',
  'edu.badge.est': 'estimate',
  'edu.badge.model': 'model',
  'edu.badge.src.tip': 'Sourced value. Opens the source in a new tab.',
  'edu.badge.est.tip': 'Estimate: {note}',
  'edu.badge.model.tip': 'Computed by the liftoff model from spec values.',
  'edu.differs.mass': 'Sources differ: one review quotes {m0_pub} t, while the listed parts add up to {m0_sum} t (several of them estimates). A value between the two is used.',
  'edu.differs.thrust': 'Sources differ: some quote {raptor_tf_alt} tf per engine, and one flight report says about {thrust_report_Mlbf} million lbf in total. {raptor_tf} tf matches the {thrust} MN total listed for Block 3.',
  'edu.differs.pc': 'Sources differ: {pc} bar or {pc_alt} bar. The lower figure is used.',
  'edu.differs.isp': 'Sources differ: 330 s or 350 s for sea level. The lower figure is used.',
  'edu.differs.label': 'sources differ',
  'edu.card.keynums': 'Key numbers',
  'edu.card.flyto': 'Fly to this',
  'edu.card.close': 'Close card',
  'edu.card.aria': 'Details: {title}',

  // ── moment tab ───────────────────────────────────────────────────────────────────────────
  'edu.layers': 'Overlays',
  'edu.layer.forces': 'Force arrows',
  'edu.layer.sound': 'Sound front',
  'edu.moment.intro': 'The picture is frozen {tf} s after release, when the engine plane is {alt_tf} m above the ground. These numbers come from a simple model and are computed for exactly that instant.',
  'edu.tile.time': 'Time after release',
  'edu.tile.alt': 'Engine-plane altitude',
  'edu.tile.vel': 'Velocity',
  'edu.tile.acc': 'Net acceleration',
  'edu.tile.tw': 'Thrust / weight',
  'edu.tile.mass': 'Mass',
  'edu.tile.burned': 'Propellant burned',
  'edu.tile.mdot': 'Mass flow',
  'edu.tile.ve': 'Exhaust velocity',
  'edu.tile.thrust': 'Thrust',
  'edu.tile.vel.sub': '{kmh} km/h',
  'edu.tile.acc.sub': '{g} g felt aboard',
  'edu.tile.tw.sub': 'at release {tw0}',
  'edu.tile.mass.sub': 'at release {m0} t',
  'edu.tile.burned.sub': 'so far since ignition',
  'edu.tile.mdot.sub': 'oxygen {lox} + methane {ch4}',
  'edu.tile.ve.sub': 'Isp {isp} s',
  'edu.tile.thrust.sub': 'weight {weight} MN',
  'edu.tile.alt.sub': '{rise} m above the mount',
  'edu.tile.time.sub': 'ignition was T−{lead} s',
  'edu.unit.s': 's',
  'edu.chart.title': 'The first minute',
  'edu.chart.hint': 'Point at a chart to read any moment. The orange line is this frozen instant.',
  'edu.chart.alt': 'Altitude',
  'edu.chart.vel': 'Velocity',
  'edu.chart.acc': 'Net acceleration',
  'edu.chart.mass': 'Mass',
  'edu.chart.note': 'One-dimensional vertical-ascent model. The throttle-down after T+{bucket} s is a placeholder, not SpaceX data, so read the right-hand side as illustrative.',
  'edu.chart.table': 'Table view',
  'edu.chart.aria': '{name} against time after release, 0 to 60 seconds. At the frozen instant it is {value}.',
  'edu.chart.freeze': 'now',
  'edu.chart.col.t': 'T+ (s)',
  'edu.chart.col.alt': 'Altitude (m)',
  'edu.chart.col.vel': 'Velocity (m/s)',
  'edu.chart.col.acc': 'Accel. (m/s²)',
  'edu.chart.col.mass': 'Mass (t)',

  // ── force vectors and sound front (3D labels) ────────────────────────────────────────────
  'edu.force.thrust': 'Thrust',
  'edu.force.weight': 'Weight',
  'edu.force.net': 'Net force',
  'edu.force.com': 'Centre of mass (est.)',
  'edu.force.plane': 'Engine plane',
  'edu.force.scale': 'Arrow length: 1 MN = 1 m. Thrust and weight are drawn side by side for clarity; both really act along the axis.',
  'edu.force.ratio': '{ratio} × weight',
  'edu.sound.label': 'Sound front, {r} km',
  'edu.sound.sub': 'sound of ignition, made {lead} s before release',

  // ── walk HUD ─────────────────────────────────────────────────────────────────────────────
  'edu.hud.title': 'Where you stand',
  'edu.hud.dist': 'Distance to the vehicle',
  'edu.hud.ground': 'Distance to the pad',
  'edu.hud.reached': 'The sound has reached you',
  'edu.hud.reached.sub': 'Ignition sound arrived at T{t} s, before the frozen instant.',
  'edu.hud.notyet': 'The sound has not reached you yet',
  'edu.hud.notyet.sub': 'It arrives in {s} s, at T+{t} s. You are seeing the rocket before you can hear it.',
  'edu.hud.spl': 'Loudness at this spot',
  'edu.hud.spl.pending': 'Loudness when it arrives',
  'edu.hud.band.faint': 'faint',
  'edu.hud.band.loud': 'loud',
  'edu.hud.band.painful': 'very loud, damages hearing within minutes',
  'edu.hud.band.damaging': 'painful, damages hearing within seconds',
  'edu.hud.band.extreme': 'can rupture eardrums',
  'edu.hud.heat': 'Radiant heat',
  'edu.hud.heat.sun': '{x} × sunlight',
  'edu.hud.heat.less': 'less than sunlight',
  'edu.hud.est': 'Estimates: free-field spreading blended toward measured far-field levels; inverse-square heat.',
  'edu.hud.aria': 'Walk readout',

  // ── sources tab ──────────────────────────────────────────────────────────────────────────
  'edu.src.intro': 'Every number in this mode is read from one spec file. Values with a link are sourced. Values marked estimate are reasoned, and the note says how.',
  'edu.src.flight.title': 'Which flight is this?',
  'edu.src.flight.body': 'Flight 14 (Booster 21 / Ship 41, Block 3, Starbase Pad 2, liftoff 2026-09-28 12:48:59 UTC), about 85 % sure. It is inferred from the lighting and timing: low warm sun from the east about 30 minutes after sunrise (sun altitude {sun_alt}°), the Pad 2 tower, V3 proportions, and a post timestamp on launch day (time zone unknown). It is not read from a caption, and the original post was not found. Flights 12 and 13 used the same pad and hardware but flew in the late afternoon, with the sun high in the west. Everything specific to the flight (timings, payload, the booster\'s ending) holds only if the identification is right.',
  'edu.src.decisions.title': 'Where the research disagreed',
  'edu.src.dec.thrust': 'Raptor 3 thrust: 250 tf chosen over the 280 tf press figure, because 33 × 250 tf gives the 80.8 MN listed for Block 3. One Flight 14 news report says about {thrust_report_Mlbf} million lbf in total, which does not match and was not reconciled.',
  'edu.src.dec.mass': 'Liftoff mass: {m0} t chosen between one review\'s {m0_pub} t and the {m0_sum} t sum of the listed parts, several of which are estimates. Across that range the frozen moment moves between {tf_light} and {tf_heavy} s.',
  'edu.src.dec.tower': 'Tower height: 144.5 m from OpenStreetMap and the FAA filing, over a 130 m guess from the photo.',
  'edu.src.dec.sun': 'Sun: altitude and azimuth were computed for the pad and time, not taken from the estimates in the notes.',
  'edu.src.dec.height': 'Booster height in the photo: 158 m, recomputed with the calibrated camera (earlier guesses were 140 and 160 m).',
  'edu.src.dec.ship': 'Ship length: 52.1 m (stack minus booster), over the 61 m listed by one page.',
  'edu.src.dec.freeze': 'Freeze time: 7.2 s in the spec. The liftoff model recomputes it from the physics; the test that checks it allows 0.3 s.',
  'edu.src.model.title': 'How the liftoff model works',
  'edu.src.model.body': 'A vertical point-mass model integrated with a fourth-order Runge–Kutta step of 0.01 s from release at full thrust. Thrust is mass flow × exhaust velocity plus a small pressure term that grows as the air thins. Drag uses Cd 0.8 in an exponential atmosphere, and gravity falls slowly with height. It starts on the {olm_h} m launch mount (its height is an estimate). The gravity-turn kick after T+10 s and the throttle-down after T+{bucket} s are not measured, so only the first ten seconds are firm, and the model\'s dynamic-pressure peak comes earlier than the real one.',
  'edu.src.values.title': 'Values shown in this mode',
  'edu.src.col.value': 'Value',
  'edu.src.col.status': 'Status',
  'edu.src.model.note': 'Computed by the liftoff model from these inputs.',
  'edu.src.open': 'Open source',

  // ── hotspot cards ────────────────────────────────────────────────────────────────────────
  'edu.hotspot.booster.short': 'Booster',
  'edu.hotspot.booster.title': 'Super Heavy, the first stage',
  'edu.hotspot.booster.body': 'Super Heavy is the first stage (the booster): {h_booster} m tall and {dia} m wide, built from stainless steel rings. Its {n_eng} Raptor engines burn about {mdot} tonnes of propellant every second (calculated from thrust and specific impulse), and the tanks hold roughly {prop_b} tonnes of liquid oxygen and liquid methane, about two thirds of the whole stack\'s mass at release. It is designed to fly back and be caught by the tower, which earlier boosters have already done, so it can be reused instead of thrown away. Most of what you see here is tank: the frosted lower part holds the liquid oxygen.',
  'edu.hotspot.ship.short': 'Ship',
  'edu.hotspot.ship.title': 'Starship, the second stage',
  'edu.hotspot.ship.body': 'The black upper part is Starship itself, the second stage. It has {n_ship_eng} Raptor engines: three at sea level and three optimised for vacuum. Its windward side is covered with about {tiles} heat-shield tiles so it can survive re-entry at orbital speed. In Block 3 it carries about {prop_s} tonnes of propellant. If this is Flight 14, as is likely, it also carries 26 Starlink V3 satellites (an estimated {payload} tonnes). Right now it is only a passenger: its own engines light at hot staging, about T+{t_stage} s.',
  'edu.hotspot.raptors.short': '33 Raptors',
  'edu.hotspot.raptors.title': '33 Raptor engines',
  'edu.hotspot.raptors.body': 'Each Raptor 3 makes about {raptor_tf} tonnes-force at sea level (some sources say {raptor_tf_alt}) from a combustion chamber at about {pc} bar, more than 300 times atmospheric pressure. Methane and oxygen burn in a full-flow staged-combustion cycle: all the propellant passes through the turbines and then burns in the chamber, so none is dumped as turbine exhaust. All {n_eng} together give {thrust} MN, about {thrust_Mlbf} million pounds-force, making this the most powerful rocket ever flown. Twenty outer engines are fixed; the thirteen inner ones swivel (gimbal) to steer the vehicle.',
  'edu.hotspot.gridfins.short': 'Grid fins',
  'edu.hotspot.gridfins.title': 'Grid fins',
  'edu.hotspot.gridfins.body': 'Near the top of the booster sit {fins} lattice panels, about {fin_scale} times larger than the four fins on earlier boosters. For most of the climb they are not needed. After the ship separates they steer the booster back down, working with the engine gimbals like the controls of a falling rocket. On Block 3 they are integrated with the catch pins that the tower\'s arms grab. At this resolution the fins are barely visible in the photograph, so their position and size here are estimates.',
  'edu.hotspot.hotstage.short': 'Hot staging',
  'edu.hotspot.hotstage.title': 'The hot-staging ring',
  'edu.hotspot.hotstage.body': 'The top of the booster is a vented structure with about {vents} openings (the count is an estimate). At about T+{t_meco} s most booster engines shut down, and the ship lights its own while still attached. The two separate a few seconds later, around T+{t_stage} s on Flight 14 (if that identification is right). The ship\'s exhaust blows out through the vents. Because the ship is already firing when it lets go, its propellant stays settled in the tanks and no separate separation rockets are needed. The altitude at this point, roughly {meco_alt} km, is an estimate.',
  'edu.hotspot.flaps.short': 'Flaps',
  'edu.hotspot.flaps.title': 'The ship\'s flaps',
  'edu.hotspot.flaps.body': 'The ship has {n_aft_flaps} large flaps near its engines, about {aft_w} by {aft_h} m, and {n_fwd_flaps} smaller ones near the nose, about {fwd_w} by {fwd_h} m (all sizes are estimates). On the way up they are folded flat against the hull and are just along for the ride. During re-entry they are the ship\'s steering. It falls belly-first like a skydiver, and the flaps move to hold that pose and to steer, before the engines flip it upright for landing.',
  'edu.hotspot.tiles.short': 'Heat tiles',
  'edu.hotspot.tiles.title': 'Heat-shield tiles',
  'edu.hotspot.tiles.body': 'About {tiles} hexagonal tiles cover the windward side of the ship, the side that meets the air first on re-entry. Each is about {tile_cm} cm across (an estimate), with a gap of about {gap_mm} mm so the ceramic can expand when hot. They look black because of their coating. The opposite side is mostly bare stainless steel, so the ship in the photo is probably showing its tiled side. The tiles are rated for about {tile_c} °C, close to where stainless steel melts, so without them the hull could not survive re-entry.',
  'edu.hotspot.frost.short': 'Frost',
  'edu.hotspot.frost.title': 'Frost on the tanks',
  'edu.hotspot.frost.body': 'Liquid oxygen boils at about −183 °C and liquid methane at about −162 °C. The tank wall is almost as cold, so water vapour in the humid Gulf air freezes onto it: mostly as frost, where vapour turns straight into ice crystals, plus droplets that condense and then freeze. The lower part of the booster, roughly the bottom {frost_pct} % below about {frost_h} m, holds the liquid oxygen and is the thickest and brightest. The upper part is darker and thinner. As the rocket accelerates and vibrates, sheets of ice crack off and fall away.',
  'edu.hotspot.tower.short': 'Tower',
  'edu.hotspot.tower.title': 'The launch tower',
  'edu.hotspot.tower.body': 'The tower is about {tower_h} m tall, including its lightning masts, and carries the two large arms called chopsticks. It stacks the rocket and catches returning boosters; the first catch was in October 2024. In this frozen instant, {tf} s after release, the booster\'s engine plane has just climbed past the tower top, moving only about {v_tf_kmh} km/h. The tower survives the launch because the rocket climbs away from it, the mount and flame trench turn the exhaust sideways, and a water deluge absorbs heat.',
  'edu.hotspot.chopsticks.short': 'Chopsticks',
  'edu.hotspot.chopsticks.title': 'The chopstick arms',
  'edu.hotspot.chopsticks.body': 'Two steel arms ride on a carriage that in the photo is about {carriage_h} m up the tower. Each arm is about {arm} m long and they reach about {reach} m from the tower face (estimates from a crowd-sourced map). They lift boosters and ships onto the mount and close around returning boosters to catch them by their pins. Here they are parked wide open, about {span} m tip to tip, so the rocket passes cleanly. The hanging boom at about {boom_h} m is probably a service arm.',
  'edu.hotspot.olm.short': 'Launch mount',
  'edu.hotspot.olm.title': 'The orbital launch mount',
  'edu.hotspot.olm.body': 'The rocket stood on a raised, water-cooled steel deck about {olm_h} m above the ground (an estimate; no published figure was found), with a round opening under the engines and twenty hold-down clamps. Pad 2 was designed after the first Starship launch blasted concrete over kilometres. Water is released from several points and the runoff goes to a pond; a July 2026 test was reported on social media at {flow_gpm} US gallons per minute, which is unconfirmed. The deck is roughly {olm_w} m square, also an estimate. Because it is {olm_h} m up, the engine plane started {olm_h} m above the ground.',
  'edu.hotspot.trench.short': 'Flame trench',
  'edu.hotspot.trench.title': 'The flame trench',
  'edu.hotspot.trench.body': 'Under the mount a concrete trench, lined with stainless steel and cooled by water, catches the exhaust. Its size is an estimate, about {tr_l} m long, {tr_w} m wide and {tr_d} m deep, running roughly east to west, and its diverter splits the jet into two streams. That is why the two huge clouds in the photo billow left and right of the rocket. Without a trench the exhaust would hit flat ground, dig a crater and throw debris for kilometres, as happened on the first flight.',
  'edu.hotspot.tankfarm.short': 'Tank farm',
  'edu.hotspot.tankfarm.title': 'The tank farm',
  'edu.hotspot.tankfarm.body': 'A few hundred metres east of the pad, at its nearest about {tank_dist} m away, stands the tank farm that feeds the rocket. On the map it shows about {lox_n} horizontal tanks for liquid oxygen and nitrogen, each about {lox_d} m wide and {lox_l} m long, {ch4_n} for liquid methane, {water_n} water tanks for the deluge and {vap_n} vaporisers (crowd-sourced counts). Loading about {prop_total} tonnes of cold propellant takes about 45 minutes before launch. In the photo view it is hidden behind the steam.',
  'edu.hotspot.plume.short': 'Plume',
  'edu.hotspot.plume.title': 'The exhaust plume',
  'edu.hotspot.plume.body': 'Behind each engine the gas moves at about {ve_km} km/s, roughly ten times the speed of sound in air, and the merged flame here reaches about {rise_tf} m down to the mount. Methane burns with little soot, so the core is only faintly luminous and looks pale violet-pink in the photo, nothing like the sooty orange of kerosene rockets. Its temperature at the nozzle exit is still about {t_exit} K after expanding from about {t_chamber} K in the chamber (both are estimates).',
  'edu.hotspot.machdiamonds.short': 'Mach diamonds',
  'edu.hotspot.machdiamonds.title': 'Mach diamonds',
  'edu.hotspot.machdiamonds.body': 'Each jet leaves its nozzle at a different pressure from the air around it. Near sea level the Raptor exit pressure is estimated at about {exit_p} bar against 1.01 bar outside, so the jet is slightly overexpanded. Oblique shock waves form at the nozzle lip, cross the jet and bounce off its boundary as expansion waves, and the pattern repeats down the jet. Each cell is a shock diamond, brighter because the gas in it is compressed and hotter. As the rocket climbs, the outside pressure drops below the exit pressure, the jet becomes underexpanded, and the cells stretch and fade.',
  'edu.hotspot.steam.short': 'Steam clouds',
  'edu.hotspot.steam.title': 'The steam clouds',
  'edu.hotspot.steam.body': 'Most of the giant clouds are water, not smoke. The FAA\'s planning figure is up to about {water_gal} US gallons ({water_ml} million litres) sprayed onto the mount and the trench, and SpaceX estimated that about {vap_pct} % of it turns to steam, which condenses into droplets in the cool humid air. The exhaust itself adds less: at most about {h2o_tps} tonnes of water and {co2_tps} tonnes of carbon dioxide per second. The orange is low morning sun, at only {sun_alt}° above the horizon, plus glow from the plume.',
  'edu.hotspot.fireball.short': 'Fireball',
  'edu.hotspot.fireball.title': 'The fireball at the base',
  'edu.hotspot.fireball.body': 'Where the plume hits the deck and trench it turns sideways and spreads. The exhaust is fuel-rich, with a mixture ratio of {of} against a perfect 4.0, so leftover carbon monoxide, hydrogen and methane meet the air and burn again. This afterburning heats the gas, and most of the bright yellow-orange glare at the foot of the column is thought to come from tiny hot particles in it, such as soot and pad dust. It is hotter and brighter than the pale plume above, it is lit from inside, and it lights the steam around it.',
  'edu.hotspot.soundfront.short': 'Sound front',
  'edu.hotspot.soundfront.title': 'The sound front',
  'edu.hotspot.soundfront.body': 'Sound travels at only about {c} m/s in warm air (25 °C is assumed). The engines ignite {lead} s before release, so the sound of ignition has been spreading for {lead} s plus {tf} s and is now a sphere about {r_tf_km} km in radius. Inside it the noise is overwhelming: about {spl100} dB at 100 m by a simple estimate, up to near {near_db} dB close to the plume. On Flight 5 in 2024, researchers measured about {spl10k} dB at 10 km and {spl20k} dB at 20 km. Beyond the front you would see the rocket well before you heard it.',

  // ── explainers ───────────────────────────────────────────────────────────────────────────
  'edu.ex.intro': 'Short explanations of the physics in this frame. The numbers update from the spec.',
  'edu.ex.tw.title': 'Why a thrust-to-weight of 1.5 makes a slow start',
  'edu.ex.tw.body': 'At release the rocket weighs about {w0} MN (mass × gravity) and the engines push with {thrust} MN. Only the difference accelerates it: a = g × (T/W − 1) = 9.8 × ({tw0} − 1) = {a0} m/s², about {g_net0} g.\n\nA passenger would feel {g0_load} g, because the seat has to hold them up and accelerate them, so it pushes with {g0_load} times their weight. Distance grows roughly as ½ a t², so {rise_tf} m takes about {tf} s, and the speed is only {v_tf} m/s ({v_tf_kmh} km/h). The rocket gets lighter by {mdot} tonnes every second, so the acceleration keeps growing.',
  'edu.ex.tw.cap': 'Forces at release, with the ground pressing back until liftoff.',
  'edu.ex.tw.slider': 'Liftoff mass',
  'edu.ex.tw.result': 'With {m} t the engine plane reaches the frozen height at T+{tf} s, at {v} m/s, with T/W {tw} at release.',
  'edu.ex.isp.title': 'Thrust from momentum, and what Isp means',
  'edu.ex.isp.body': 'A rocket pushes because it throws mass backwards. Thrust is a momentum flow plus a pressure term, F = ṁ × v_jet + (pₑ − pₐ) × Aₑ. Engineers bundle both into one effective exhaust velocity, vₑ = Isp × g₀ = {isp} s × 9.81 m/s² = {ve} m/s. With {mdot} tonnes per second that gives {thrust} MN. Isp is like a fuel economy figure: seconds of thrust per unit weight of propellant.\n\nThe pressure term is small here. At {alt_tf} m thrust has risen only {gain_tf} %. In vacuum this model adds {gain_vac} %, to about {thrust_vac} MN.',
  'edu.ex.isp.cap': 'Mass flow times exhaust velocity is thrust.',
  'edu.ex.rocketeq.title': 'The rocket equation',
  'edu.ex.rocketeq.body': 'Tsiolkovsky\'s equation says the speed a rocket gains is Δv = vₑ × ln(m₀ / m₁). With vₑ = {ve_km} km/s, a start mass of {m0} t and about {m_meco} t left when the booster\'s engines stop (mass ratio {mass_ratio}), the ideal Δv is {dv_ideal} km/s. The end mass assumes full flow for {t_meco} s.\n\nGravity and drag take a large share, so the real speed at staging is only about {dv_meco} km/s (an estimate). That is why rockets are staged: throwing away the empty booster stops you carrying its dry mass all the way to orbit.',
  'edu.ex.rocketeq.cap': 'Mass ratio decides how much speed the propellant can buy.',
  'edu.ex.steam.title': 'Why the clouds are white and orange-lit',
  'edu.ex.steam.body': 'Turning about {steam_t} tonnes of water into steam takes about {vap_tj} TJ, which the plume\'s {chem_gw} GW of chemical power could supply in only about {vap_s} seconds. The steam meets cool humid air and condenses into droplets a few to tens of micrometres wide. Droplets much larger than the wavelength of light scatter every colour about equally (Mie scattering), so the cloud looks white. It is not smoke.\n\nAbout {sun_alt}° above the horizon, the sun shines through a thick layer of air that removes blue. The clouds catch that orange light, and the plume adds its own glow from below.',
  'edu.ex.steam.cap': 'Mie scattering from cloud droplets is nearly colour-blind.',
  'edu.ex.diamonds.title': 'Overexpanded nozzles and Mach diamonds',
  'edu.ex.diamonds.body': 'Whether a jet is over- or underexpanded depends on its exit pressure against the outside air. Here the exit pressure is estimated at about {exit_p} bar and the air is 1.01 bar, so the jet is overexpanded: oblique shocks at the nozzle lip squeeze it, it overshoots, and an expansion then releases it. Each squeeze and release makes one bright cell.\n\nThe outside pressure falls as the rocket rises, and above about {match_km} km it drops below the exit pressure, so the jet becomes underexpanded and the cells grow longer and fade. Near the mount the patterns of 33 engines overlap, so single diamonds are hard to pick out.',
  'edu.ex.diamonds.cap': 'Shocks and expansions repeat along the jet.',
  'edu.ex.colour.title': 'Plume colour and afterburning',
  'edu.ex.colour.body': 'The engines run fuel-rich (oxygen to fuel {of} against 4.0 for perfect burning), and methane makes little soot. So the core is only weakly luminous. Its violet-pink tint comes from blue emission by excited CH and CO₂ molecules and from the bright shock cells, and the camera\'s colour balance adds to it.\n\nWhere the leftover carbon monoxide, hydrogen and methane mix with air they burn again. This afterburning heats the gas and any tiny particles in it (soot, dust), and hot particles glow yellow-orange like a flame. Hot steam and carbon dioxide radiate mostly infrared, which we cannot see. The ground glare at the base of the column is that afterburning fire, plus steam lit from inside.',
  'edu.ex.colour.cap': 'Core: pale violet. Mixing zone: yellow-orange.',
  'edu.ex.sound.title': 'The sound front',
  'edu.ex.sound.body': 'Sound emitted at time t reaches distance r at time t + r/c. The engines lit {lead} s before release, so the front of the ignition sound has radius c × (t + {lead} s) = {c} m/s × ({tf} + {lead}) s = {r_tf_km} km.\n\nThe source is about {lw} dB of sound power. That is an estimate that assumes {eff_pct} % of the {jet_gw} GW jet power becomes sound (NASA\'s rule of thumb is 0.2 to 0.8 %). Simple spreading predicts {spl_free10k} dB at 10 km, but measurement on Flight 5 found {spl10k} dB. The plume sends most of its sound out at an angle rather than evenly, the deluge water and the pad take some of it, and air, ground and weather weaken the rest. The diagram shows both curves.',
  'edu.ex.sound.cap': 'Loudness against distance, model and measurement.',
  'edu.ex.staging.title': 'Max-Q and hot staging',
  'edu.ex.staging.body': 'Dynamic pressure, q = ½ ρ v², is the air load on the rocket. It rises with speed, then falls as the air thins, so it peaks about a minute after liftoff (around T+{t_maxq} s on Flight 14). A simple vertical model gives roughly {maxq_kpa} kPa, only an order-of-magnitude guide. Engines typically throttle down through that peak to keep the loads down.\n\nAt about T+{t_meco} s the booster shuts down most of its engines, the ship lights while still attached, and they separate around T+{t_stage} s: hot staging.',
  'edu.ex.staging.cap': 'Events of the first {t_stage} seconds.',
  'edu.ex.catch.title': 'The tower catch',
  'edu.ex.catch.body': 'Instead of landing on legs, the booster comes back to the tower and the chopstick arms close around it, holding it by {pins} catch pins near the top, at about {pin_h} m up. With no legs to carry, the booster is lighter, and it can be lifted straight back onto the mount for another flight.\n\nA catch needs precision to a fraction of a metre. Boosters have been caught since Flight 5 in October 2024. If this is Flight 14, the booster instead made a landing burn and a controlled splashdown in the Gulf, and no ship had been caught by then.',
  'edu.ex.catch.cap': 'Pins on the booster, arms on the tower.',
  'edu.ex.frost.title': 'Why the rocket is frosted',
  'edu.ex.frost.body': 'Liquid oxygen boils at about −183 °C and liquid methane at about −162 °C. The steel tank wall is almost as cold, so water vapour in the humid Gulf air freezes onto it, mostly as frost (vapour turning straight into ice) and as condensed droplets that freeze. The boundary between the frosty oxygen tank and the thinner methane tank is at about {frost_h} m in the photo.\n\nFrost is a useful clue: it shows where the cold liquid sits. It also cracks and flakes off as the rocket vibrates and speeds up.',
  'edu.ex.frost.cap': 'Water vapour freezes onto the cold tank wall.',
  'edu.ex.heat.title': 'Radiant heat',
  'edu.ex.heat.body': 'The plume glows, so it radiates heat as well as noise. A rough order-of-magnitude estimate gives about {q100} kW/m² at 100 m, roughly {q100} times full sunlight, and only {q1k} kW/m² at 1 km, less than sunlight (about 1 kW/m²). The flux falls with the square of distance, and the estimate ignores steam and absorption by the air.\n\nThe energy comes from about {chem_gw} GW of chemical power, as much as about {chem_gw} large 1 GW power stations. That is one reason the area is cleared for kilometres, along with noise and flying debris, while distant viewers feel only a brief glow.',
  'edu.ex.heat.cap': 'Inverse-square fall-off of radiant heat.',
  'edu.ex.fuel.title': 'Methane and oxygen',
  'edu.ex.fuel.body': 'Raptor burns liquid methane with liquid oxygen at a mass ratio of {of} to 1, which is fuel-rich compared with the perfect 4.0. Methane is cheap, burns cleaner than kerosene and can be made on Mars from carbon dioxide and water.\n\nAbout {mdot_lox} tonnes of oxygen and {mdot_ch4} tonnes of methane leave every second, so {prop_b} tonnes would last about {burn_s} seconds at full thrust. The real engine cut-off is around T+{t_meco} s, which would leave roughly {reserve} tonnes for the boostback and landing burns; real flow and throttle settings are not published, so this is only a check.',
  'edu.ex.fuel.cap': 'Mass flow of oxygen and methane.',
  'edu.dia.weight': 'Weight',
  'edu.dia.thrust': 'Thrust',
  'edu.dia.net': 'Net',
  'edu.dia.ground': 'ground',
  'edu.dia.nozzle': 'nozzle',
  'edu.dia.shock': 'shock',
  'edu.dia.expansion': 'expansion',
  'edu.dia.core': 'core',
  'edu.dia.mix': 'mixing zone',
  'edu.dia.pad': 'pad',
  'edu.dia.ignition': 'ignition',
  'edu.dia.now': 'now',
  'edu.dia.free': 'free-field model',
  'edu.dia.measured': 'measured',
  'edu.dia.booster': 'booster',
  'edu.dia.ship': 'ship',
  'edu.dia.arm': 'arm',
  'edu.dia.pin': 'pin',
  'edu.dia.lox': 'liquid oxygen',
  'edu.dia.ch4': 'methane',
  'edu.dia.frost': 'frost',
  'edu.dia.km': 'km',
  'edu.dia.steam': 'steam',
  'edu.dia.droplets': 'droplets',
  'edu.dia.sun': 'low sun',
  'edu.dia.maxq': 'max-Q',
  'edu.dia.meco': 'MECO',
  'edu.dia.stage': 'staging',
  'edu.dia.heat': 'heat flux',
  'edu.dia.sunlevel': 'sunlight',
  'edu.dia.oxygen': 'oxygen',
  'edu.dia.methane': 'methane',
  'edu.dia.burn': 'burn',
  'edu.dia.thrustlabel': 'thrust',

  // ── spec key labels ──────────────────────────────────────────────────────────────────────
  'edu.k.booster_height_m': 'Booster height', 'edu.k.stack_height_m': 'Stack height', 'edu.k.ship_height_m': 'Ship height',
  'edu.k.diameter_m': 'Diameter', 'edu.k.booster_engines': 'Booster engines', 'edu.k.ship_engines': 'Ship engines',
  'edu.k.booster_prop_mass_b3_t': 'Booster propellant', 'edu.k.ship_prop_mass_b3_t': 'Ship propellant',
  'edu.k.booster_dry_mass_b3_t': 'Booster dry mass', 'edu.k.ship_dry_mass_b3_t': 'Ship dry mass', 'edu.k.payload_mass_f14_t': 'Payload',
  'edu.k.liftoff_mass_used_t': 'Liftoff mass', 'edu.k.liftoff_mass_published_t': 'Liftoff mass, one review', 'edu.k.liftoff_mass_sum_of_parts_t': 'Liftoff mass, sum of parts',
  'edu.k.liftoff_thrust_b3_MN': 'Liftoff thrust', 'edu.k.liftoff_thrust_b3_Mlbf': 'Liftoff thrust (imperial)',
  'edu.k.liftoff_tw_central': 'Thrust / weight at release', 'edu.k.liftoff_tw_range_low': 'Thrust / weight, low', 'edu.k.liftoff_tw_range_high': 'Thrust / weight, high',
  'edu.k.raptor3_thrust_sl_tf': 'Raptor 3 thrust, sea level', 'edu.k.raptor3_thrust_sl_alt_tf': 'Raptor 3 thrust, press figure',
  'edu.k.raptor3_chamber_pressure_bar': 'Chamber pressure', 'edu.k.raptor3_chamber_pressure_alt_bar': 'Chamber pressure, alternative',
  'edu.k.raptor3_engine_mass_kg': 'Engine mass', 'edu.k.raptor_of_ratio': 'Oxygen to fuel ratio',
  'edu.k.raptor3_isp_sl_used_s': 'Specific impulse, sea level', 'edu.k.raptor3_isp_vac_s': 'Specific impulse, vacuum',
  'edu.k.raptor_exhaust_velocity_sl_mps': 'Exhaust velocity', 'edu.k.raptor_chamber_temperature_K': 'Chamber temperature',
  'edu.k.raptor_exit_static_temperature_K': 'Nozzle exit temperature', 'edu.k.raptor_exit_pressure_bar': 'Nozzle exit pressure',
  'edu.k.raptor_exit_mach': 'Exit Mach number', 'edu.k.raptor_nozzle_exit_diameter_m': 'Nozzle exit diameter',
  'edu.k.raptor_nozzle_expansion_ratio': 'Nozzle expansion ratio',
  'edu.k.mdot_booster_total_kgps': 'Propellant flow, booster', 'edu.k.mdot_lox_total_kgps': 'Oxygen flow', 'edu.k.mdot_ch4_total_kgps': 'Methane flow',
  'edu.k.booster_full_thrust_burn_time_s': 'Full-thrust burn time', 'edu.k.jet_mechanical_power_GW': 'Jet power', 'edu.k.chemical_power_GW': 'Chemical power',
  'edu.k.vac_thrust_booster_MN': 'Vacuum thrust', 'edu.k.thrust_gain_150m_pct': 'Thrust gain at 150 m', 'edu.k.engine_start_lead_s': 'Ignition before release',
  'edu.k.tower_height_used_m': 'Tower height', 'edu.k.olm_height_m': 'Launch mount height', 'edu.k.base_rise_to_tower_top_m': 'Rise to the tower top',
  'edu.k.t_base_at_tower_top_s': 'Time to tower top', 'edu.k.v_base_at_tower_top_mps': 'Speed at the tower top', 'edu.k.a_net_at_tower_top_mps2': 'Net acceleration there',
  'edu.k.max_q_time_f14_s': 'Max-Q time', 'edu.k.max_q_model_kPa': 'Max-Q, simple model', 'edu.k.meco_time_f14_s': 'Booster engine cut-off',
  'edu.k.hot_staging_time_f14_s': 'Hot staging', 'edu.k.meco_alt_est_km': 'Altitude at cut-off', 'edu.k.meco_speed_est_mps': 'Speed at cut-off',
  'edu.k.deluge_water_pad1_gal': 'Deluge water (Pad 1)', 'edu.k.deluge_water_pad1_kg': 'Deluge water mass', 'edu.k.deluge_vaporised_fraction': 'Turned to steam',
  'edu.k.deluge_pad2_test_flow_gpm': 'Pad 2 test flow', 'edu.k.deluge_pad2_test_flow_m3ps': 'Pad 2 test flow',
  'edu.k.deluge_vaporisation_energy_J': 'Energy to vaporise the water', 'edu.k.combustion_h2o_tps': 'Water from combustion', 'edu.k.combustion_co2_tps': 'Carbon dioxide from combustion',
  'edu.k.launch_table_mass_pad1_t': 'Launch table mass (Pad 1)',
  'edu.k.sound_speed_25C_mps': 'Speed of sound, 25 °C', 'edu.k.sound_front_radius_at_photo_m': 'Sound-front radius, estimate', 'edu.k.acoustic_eff_central': 'Acoustic efficiency',
  'edu.k.sound_power_level_dB': 'Sound power level', 'edu.k.spl_100m_dB': 'Loudness at 100 m', 'edu.k.spl_1km_dB': 'Loudness at 1 km',
  'edu.k.spl_10km_measured_dB': 'Loudness at 10 km, measured', 'edu.k.spl_20km_measured_dB': 'Loudness at 20 km, measured',
  'edu.k.near_field_dB': 'Near-field loudness', 'edu.k.faa_lmax_contour_dB': 'FAA noise contour',
  'edu.k.plume_radiant_flux_100m_kWm2': 'Radiant heat at 100 m', 'edu.k.plume_radiant_flux_1km_kWm2': 'Radiant heat at 1 km',
  'edu.k.vehicle.ship.tile.count_windward': 'Tiles on the windward side', 'edu.k.vehicle.ship.tile.hex_size': 'Tile width', 'edu.k.vehicle.ship.tile.gap': 'Tile gap',
  'edu.k.vehicle.booster.grid_fin.count': 'Grid fins', 'edu.k.vehicle.booster.grid_fin.scale_vs_v2': 'Grid fin size vs V2', 'edu.k.vehicle.booster.grid_fin.span': 'Grid fin span',
  'edu.k.vehicle.booster.hot_stage_vent_count': 'Hot-stage vents', 'edu.k.vehicle.booster.catch_pin_count': 'Catch pins', 'edu.k.vehicle.booster.catch_pin_height': 'Catch pin height',
  'edu.k.vehicle.photo.frost_boundary_height': 'Frost boundary height', 'edu.k.vehicle.booster.frost.lox_tank_fraction_of_height': 'Frosted share of the booster',
  'edu.k.vehicle.booster.common_dome_height': 'Common dome height', 'edu.k.vehicle.ship.aft_flap.count': 'Aft flaps', 'edu.k.vehicle.ship.forward_flap.count': 'Forward flaps',
  'edu.k.pad.tower2_height': 'Tower height', 'edu.k.pad.chopstick_carriage_height_in_photo': 'Carriage height in the photo', 'edu.k.pad.chopstick_open_span_photo': 'Arms open, tip to tip',
  'edu.k.pad.chopstick_arm_length': 'Arm length', 'edu.k.pad.chopstick_reach_from_tower_face': 'Reach from the tower', 'edu.k.pad.qd_arm_boom_height_in_photo': 'Boom height',
  'edu.k.pad.vaporizers': 'Vaporisers', 'edu.k.pad.coast_distance_east': 'Distance to the coast',
  'edu.k.scene.t_freeze': 'Frozen instant', 'edu.k.scene.vehicle_base_height': 'Engine-plane height', 'edu.k.scene.olm_deck_height': 'Launch mount deck', 'edu.k.scene.sun_altitude': 'Sun altitude',
};
