// Suomenkieliset tekstit opetustilaan. Sama avainjoukko kuin content.en.ts. {nimi}-paikkamerkit
// täytetään suoraan speksistä ja nousumallista (src/edu/vars.ts), joten luvut pysyvät ajan tasalla.
// Ritiläevät: 'grid fins' -termille ei löytynyt vakiintunutta suomennosta (glossary: matala varmuus). Valittu
// 'ritiläevä', koska 'siiveke' on jo varattu Starshipin laskeutumissiivekkeille (flaps). Englanti sulkeissa.
// Iskuaaltokuvio: 'Machin timantit' on suora käännös eikä vakiintunut, joten pääterminä on 'iskuaaltokuvio'.
// Liekkikaivanto = flame trench (tehtävänannon termi; glossaryssa 'liekkikanava', matala varmuus).
// Termit noudattavat tiedostoa research/glossary-fi.json (esim. "ensimmäinen vaihe", ei "kuumaerotus").

export const fi: Record<string, string> = {
  // ── kehys ────────────────────────────────────────────────────────────────────────────────
  'edu.title': 'Opetustila',
  'edu.panel.title': 'Tämän hetken fysiikka',
  'edu.panel.aria': 'Tämän hetken fysiikka: luvut, kaaviot, selitykset ja lähteet',
  'edu.tab.moment': 'Hetki',
  'edu.tab.explain': 'Selitykset',
  'edu.tab.sources': 'Lähteet',
  'edu.collapse': 'Piilota paneeli',
  'edu.expand': 'Näytä paneeli',
  'edu.close': 'Sulje',
  'edu.exit': 'Poistu opetustilasta',
  'edu.pill': 'Tämän hetken fysiikka',
  'edu.markers.aria': 'Kohdepisteet. Valitse yksi nähdäksesi lisätiedot.',
  'edu.marker.open': 'Avaa kortti: {title}',
  'edu.cat.vehicle': 'Kantoraketti',
  'edu.cat.pad': 'Laukaisupaikka',
  'edu.cat.fx': 'Pakokaasusuihku ja pilvet',
  'edu.cat.physics': 'Fysiikka',
  'edu.badge.src': 'lähteellinen',
  'edu.badge.est': 'arvio',
  'edu.badge.model': 'malli',
  'edu.badge.src.tip': 'Lähteellinen arvo. Avaa lähteen uuteen välilehteen.',
  'edu.badge.est.tip': 'Arvio: {note}',
  'edu.badge.model.tip': 'Nousumalli laskee tämän speksin arvoista.',
  'edu.differs.mass': 'Lähteet eroavat: yksi katsaus ilmoittaa {m0_pub} t, kun luetellut osat summautuvat {m0_sum} t:ksi (monet niistä arvioita). Käytössä on arvo näiden väliltä.',
  'edu.differs.thrust': 'Lähteet eroavat: joidenkin mukaan {raptor_tf_alt} tf moottoria kohden, ja yksi lentoraportti kertoo yhteensä noin {thrust_report_Mlbf} miljoonaa paunavoimaa. Arvo {raptor_tf} tf vastaa Block 3:lle ilmoitettua kokonaisuutta {thrust} MN.',
  'edu.differs.pc': 'Lähteet eroavat: {pc} bar tai {pc_alt} bar. Käytössä on pienempi arvo.',
  'edu.differs.isp': 'Lähteet eroavat: merenpinnalla 330 s tai 350 s. Käytössä on pienempi arvo.',
  'edu.differs.label': 'lähteet eroavat',
  'edu.card.keynums': 'Keskeiset luvut',
  'edu.card.flyto': 'Lennä tähän',
  'edu.card.close': 'Sulje kortti',
  'edu.card.aria': 'Lisätiedot: {title}',

  // ── hetki-välilehti ──────────────────────────────────────────────────────────────────────
  'edu.layers': 'Peittokuvat',
  'edu.layer.forces': 'Voimanuolet',
  'edu.layer.sound': 'Ääniaaltorintama',
  'edu.moment.intro': 'Kuva on pysäytetty {tf} s vapautuksen jälkeen, kun moottoritaso on {alt_tf} m maanpinnan yläpuolella. Nämä luvut tulevat yksinkertaisesta mallista, ja ne on laskettu juuri tälle hetkelle.',
  'edu.tile.time': 'Aika vapautuksesta',
  'edu.tile.alt': 'Moottoritason korkeus',
  'edu.tile.vel': 'Nopeus',
  'edu.tile.acc': 'Kokonaiskiihtyvyys',
  'edu.tile.tw': 'Työntövoima / paino',
  'edu.tile.mass': 'Massa',
  'edu.tile.burned': 'Poltettu ajoaine',
  'edu.tile.mdot': 'Massavirta',
  'edu.tile.ve': 'Suihkunopeus',
  'edu.tile.thrust': 'Työntövoima',
  'edu.tile.vel.sub': '{kmh} km/h',
  'edu.tile.acc.sub': '{g} g tuntuu kyydissä',
  'edu.tile.tw.sub': 'vapautushetkellä {tw0}',
  'edu.tile.mass.sub': 'vapautushetkellä {m0} t',
  'edu.tile.burned.sub': 'sytytyksestä lähtien',
  'edu.tile.mdot.sub': 'happi {lox} + metaani {ch4}',
  'edu.tile.ve.sub': 'Isp {isp} s',
  'edu.tile.thrust.sub': 'paino {weight} MN',
  'edu.tile.alt.sub': '{rise} m laukaisualustan yläpuolella',
  'edu.tile.time.sub': 'sytytys oli T−{lead} s',
  'edu.unit.s': 's',
  'edu.chart.title': 'Ensimmäinen minuutti',
  'edu.chart.hint': 'Osoita kaaviota nähdäksesi minkä tahansa hetken arvon. Oranssi viiva on tämä pysäytetty hetki.',
  'edu.chart.alt': 'Korkeus',
  'edu.chart.vel': 'Nopeus',
  'edu.chart.acc': 'Kokonaiskiihtyvyys',
  'edu.chart.mass': 'Massa',
  'edu.chart.note': 'Yksiulotteinen pystysuora nousumalli. Kaasun kuristus T+{bucket} s jälkeen on paikkamerkki eikä SpaceX:n dataa, joten oikea puoli on havainnollistava.',
  'edu.chart.table': 'Taulukkonäkymä',
  'edu.chart.aria': '{name} ajan funktiona vapautuksesta 0–60 sekuntia. Pysäytetyllä hetkellä arvo on {value}.',
  'edu.chart.freeze': 'nyt',
  'edu.chart.col.t': 'T+ (s)',
  'edu.chart.col.alt': 'Korkeus (m)',
  'edu.chart.col.vel': 'Nopeus (m/s)',
  'edu.chart.col.acc': 'Kiihtyv. (m/s²)',
  'edu.chart.col.mass': 'Massa (t)',

  // ── voimavektorit ja ääniaaltorintama ────────────────────────────────────────────────────
  'edu.force.thrust': 'Työntövoima',
  'edu.force.weight': 'Paino',
  'edu.force.net': 'Kokonaisvoima',
  'edu.force.com': 'Massakeskipiste (arvio)',
  'edu.force.plane': 'Moottoritaso',
  'edu.force.scale': 'Nuolen pituus: 1 MN = 1 m. Työntövoima ja paino on piirretty vierekkäin selkeyden vuoksi; todellisuudessa molemmat vaikuttavat akselia pitkin.',
  'edu.force.ratio': '{ratio} × paino',
  'edu.sound.label': 'Ääniaaltorintama, {r} km',
  'edu.sound.sub': 'sytytyksen ääni, syntyi {lead} s ennen vapautusta',

  // ── kävelytilan mittari ──────────────────────────────────────────────────────────────────
  'edu.hud.title': 'Missä seisot',
  'edu.hud.dist': 'Etäisyys raketista',
  'edu.hud.ground': 'Etäisyys laukaisupaikasta',
  'edu.hud.reached': 'Ääni on jo tavoittanut sinut',
  'edu.hud.reached.sub': 'Sytytyksen ääni saapui hetkellä T{t} s, ennen pysäytettyä hetkeä.',
  'edu.hud.notyet': 'Ääni ei ole vielä tavoittanut sinua',
  'edu.hud.notyet.sub': 'Se saapuu {s} s kuluttua, hetkellä T+{t} s. Näet raketin ennen kuin kuulet sen.',
  'edu.hud.spl': 'Äänenvoimakkuus tässä kohdassa',
  'edu.hud.spl.pending': 'Äänenvoimakkuus, kun ääni saapuu',
  'edu.hud.band.faint': 'hiljainen',
  'edu.hud.band.loud': 'kova',
  'edu.hud.band.painful': 'erittäin kova, vaurioittaa kuuloa minuuteissa',
  'edu.hud.band.damaging': 'kivulias, vaurioittaa kuuloa sekunneissa',
  'edu.hud.band.extreme': 'voi puhkaista tärykalvot',
  'edu.hud.heat': 'Lämpösäteily',
  'edu.hud.heat.sun': '{x} × auringonvalo',
  'edu.hud.heat.less': 'vähemmän kuin auringonvalo',
  'edu.hud.est': 'Arvioita: vapaan kentän vaimeneminen yhdistettynä mitattuihin kaukokentän tasoihin; lämpö vaimenee etäisyyden neliössä.',
  'edu.hud.aria': 'Kävelymittari',

  // ── lähteet-välilehti ────────────────────────────────────────────────────────────────────
  'edu.src.intro': 'Jokainen tämän tilan luku luetaan yhdestä speksitiedostosta. Linkillä varustetut arvot ovat lähteellisiä. Arvioksi merkityt on päätelty, ja huomautus kertoo miten.',
  'edu.src.flight.title': 'Mikä lento tämä on?',
  'edu.src.flight.body': 'Lento 14 (Booster 21 / Ship 41, Block 3, Starbasen laukaisualusta 2, nousu 2026-09-28 12:48:59 UTC), noin 85 % varmuudella. Tunnistus on päätelmä valaistuksesta ja ajoituksesta: matala lämmin aurinko idästä noin 30 minuuttia auringonnousun jälkeen (auringon korkeus {sun_alt}°), laukaisualustan 2 torni, V3-mittasuhteet ja julkaisun aikaleima laukaisupäivältä (aikavyöhyke tuntematon). Sitä ei ole luettu kuvatekstistä, eikä alkuperäistä julkaisua löytynyt. Lennot 12 ja 13 käyttivät samaa alustaa ja kalustoa mutta lensivät myöhään iltapäivällä, jolloin aurinko oli korkealla lännessä. Kaikki lentokohtaiset tiedot (ajoitukset, hyötykuorma, ensimmäisen vaiheen loppu) pätevät vain, jos tunnistus on oikea.',
  'edu.src.decisions.title': 'Missä tutkimus oli ristiriidassa',
  'edu.src.dec.thrust': 'Raptor 3:n työntövoima: valittiin 250 tf eikä lehdistön 280 tf, koska 33 × 250 tf antaa Block 3:lle ilmoitetun 80,8 MN:n. Yksi lennon 14 uutisraportti puhuu noin {thrust_report_Mlbf} miljoonasta paunavoimasta yhteensä, mikä ei täsmää eikä sitä ole sovitettu yhteen.',
  'edu.src.dec.mass': 'Lähtömassa: valittiin {m0} t yhden katsauksen ilmoittaman {m0_pub} t:n ja lueteltujen osien summan {m0_sum} t:n väliltä; monet osista ovat arvioita. Tällä vaihteluvälillä pysäytetty hetki liikkuu välillä {tf_light}–{tf_heavy} s.',
  'edu.src.dec.tower': 'Tornin korkeus: 144,5 m OpenStreetMapista ja FAA:n hakemuksesta, eikä valokuvasta arvioitu 130 m.',
  'edu.src.dec.sun': 'Aurinko: korkeus ja suunta laskettiin laukaisupaikalle ja ajanhetkelle, ei otettu muistiinpanojen arvioista.',
  'edu.src.dec.height': 'Boosterin korkeus kuvassa: 158 m, laskettu uudelleen kalibroidulla kameralla (aiemmat arviot olivat 140 ja 160 m).',
  'edu.src.dec.ship': 'Toisen vaiheen pituus: 52,1 m (pino miinus ensimmäinen vaihe), eikä yhden sivun ilmoittama 61 m.',
  'edu.src.dec.freeze': 'Pysäytysaika: speksissä 7,2 s. Nousumalli laskee sen fysiikasta uudelleen; sen tarkistava testi sallii 0,3 s.',
  'edu.src.model.title': 'Miten nousumalli toimii',
  'edu.src.model.body': 'Pystysuora pistemassamalli, jota integroidaan neljännen kertaluvun Runge–Kutta-menetelmällä 0,01 s askelin täydellä työntövoimalla tapahtuvasta vapautuksesta alkaen. Työntövoima on massavirta × suihkunopeus sekä pieni painetermi, joka kasvaa ilman ohentuessa. Ilmanvastuksessa käytetään Cd-arvoa 0,8 ja eksponentiaalista ilmakehää, ja painovoima heikkenee hitaasti korkeuden mukana. Lähtö on {olm_h} m korkealta laukaisualustalta (sen korkeus on arvio). Painovoimakäännös T+10 s jälkeen ja kaasun kuristus T+{bucket} s jälkeen eivät ole mitattuja, joten vain ensimmäiset kymmenen sekuntia ovat luotettavia, ja mallin dynaamisen paineen huippu tulee todellista aiemmin.',
  'edu.src.values.title': 'Tässä tilassa näytetyt arvot',
  'edu.src.col.value': 'Arvo',
  'edu.src.col.status': 'Tila',
  'edu.src.model.note': 'Nousumalli laskee tämän näistä lähtöarvoista.',
  'edu.src.open': 'Avaa lähde',

  // ── kohdekortit ──────────────────────────────────────────────────────────────────────────
  'edu.hotspot.booster.short': 'Ensimmäinen vaihe',
  'edu.hotspot.booster.title': 'Super Heavy, ensimmäinen vaihe',
  'edu.hotspot.booster.body': 'Super Heavy on ensimmäinen vaihe (booster): {h_booster} m korkea ja {dia} m leveä, rakennettu ruostumattomista teräsrenkaista. Sen {n_eng} Raptor-moottoria polttavat noin {mdot} tonnia ajoainetta sekunnissa (laskettu työntövoimasta ja ominaisimpulssista), ja säiliöihin mahtuu noin {prop_b} tonnia nestemäistä happea ja nestemäistä metaania, eli noin kaksi kolmasosaa koko pinon massasta vapautushetkellä. Se on suunniteltu palaamaan ja tulemaan tornin kiinniottamaksi, minkä aiemmat ensimmäiset vaiheet ovat jo tehneet, joten sen voi käyttää uudelleen sen sijaan että se heitettäisiin pois. Suurin osa näkemästäsi on säiliötä: huurteinen alaosa sisältää nestemäisen hapen.',
  'edu.hotspot.ship.short': 'Toinen vaihe',
  'edu.hotspot.ship.title': 'Starship, toinen vaihe',
  'edu.hotspot.ship.body': 'Musta yläosa on itse Starship, toinen vaihe. Siinä on {n_ship_eng} Raptor-moottoria: kolme merenpinnan tasolle ja kolme tyhjiöön optimoitua. Sen tuulenpuoleinen sivu on peitetty noin {tiles} lämpösuojalaatalla, jotta se selviää paluusta ilmakehään kiertoratanopeudella. Block 3 -versiossa se kuljettaa noin {prop_s} tonnia ajoainetta. Jos kuva on lennolta 14, kuten todennäköisesti on, mukana on myös 26 Starlink V3 -satelliittia (arviolta {payload} tonnia). Juuri nyt se on vain matkustaja: sen omat moottorit syttyvät aktiivisessa vaiheiden irrotuksessa, noin hetkellä T+{t_stage} s.',
  'edu.hotspot.raptors.short': '33 Raptoria',
  'edu.hotspot.raptors.title': '33 Raptor-moottoria',
  'edu.hotspot.raptors.body': 'Jokainen Raptor 3 tuottaa merenpinnalla noin {raptor_tf} tonnivoimaa (joidenkin lähteiden mukaan {raptor_tf_alt}) palotilassa, jonka paine on noin {pc} bar, yli 300 kertaa ilmanpaine. Metaani ja happi palavat täysvirtaus-vaiheittaispolttosyklissä: kaikki ajoaine kulkee turbiinien kautta ja palaa sitten palotilassa, joten mitään ei päästetä hukkaan erillisenä turbiinin pakokaasuna. Kaikki {n_eng} yhdessä tuottavat {thrust} MN, noin {thrust_Mlbf} miljoonaa paunavoimaa, joten tämä on tehokkain koskaan lentänyt raketti. Kaksikymmentä ulkoreunan moottoria on kiinteitä; kolmetoista sisempää kääntyy (kardaaniripustus) ohjatakseen rakettia.',
  'edu.hotspot.gridfins.short': 'Ritiläevät',
  'edu.hotspot.gridfins.title': 'Ritiläevät',
  'edu.hotspot.gridfins.body': 'Ensimmäisen vaiheen yläosassa on {fins} ritiläevää (grid fins), noin {fin_scale} kertaa isompia kuin aiempien ensimmäisten vaiheiden neljä evää. Suurimman osan noususta niitä ei tarvita. Kun toinen vaihe on irronnut, ne ohjaavat ensimmäisen vaiheen takaisin alas yhdessä moottorien kääntyvien ripustusten kanssa kuin putoavan raketin ohjaimet. Block 3 -versiossa ne on integroitu kiinniottotappeihin, joista tornin varret tarttuvat kiinni. Tässä resoluutiossa evät erottuvat valokuvasta vain juuri ja juuri, joten niiden paikka ja koko ovat arvioita.',
  'edu.hotspot.hotstage.short': 'Vaiheiden irrotus',
  'edu.hotspot.hotstage.title': 'Aktiivinen vaiheiden irrotus (hot staging)',
  'edu.hotspot.hotstage.body': 'Ensimmäisen vaiheen yläpäässä on tuuletettu rakenne, jossa on noin {vents} aukkoa (lukumäärä on arvio). Noin hetkellä T+{t_meco} s ensimmäinen vaihe sammuttaa suurimman osan moottoreistaan, ja toinen vaihe sytyttää omansa vielä kiinni ollessaan. Vaiheet irtoavat toisistaan muutamaa sekuntia myöhemmin, lennolla 14 (jos tunnistus pitää paikkansa) noin hetkellä T+{t_stage} s. Toisen vaiheen pakokaasu virtaa aukkojen kautta ulos. Koska toinen vaihe palaa jo irrotessaan, sen ajoaine pysyy paikallaan säiliöissä eikä erillisiä irrotusmoottoreita tarvita. Korkeus tässä kohdassa, noin {meco_alt} km, on arvio.',
  'edu.hotspot.flaps.short': 'Siivekkeet',
  'edu.hotspot.flaps.title': 'Toisen vaiheen siivekkeet',
  'edu.hotspot.flaps.body': 'Toisessa vaiheessa on {n_aft_flaps} suurta siivekettä moottoreiden lähellä, noin {aft_w} × {aft_h} m, ja {n_fwd_flaps} pienempää nokan lähellä, noin {fwd_w} × {fwd_h} m (kaikki mitat ovat arvioita). Nousun aikana ne ovat taitettuina litteäksi rungon vasten eivätkä tee mitään. Paluussa ne ovat aluksen ohjaus. Se putoaa vatsa edellä kuin laskuvarjohyppääjä, ja siivekkeet liikkuvat pitääkseen asennon ja ohjatakseen, ennen kuin moottorit kääntävät aluksen pystyyn laskeutumista varten.',
  'edu.hotspot.tiles.short': 'Suojalaatat',
  'edu.hotspot.tiles.title': 'Lämpösuojalaatat',
  'edu.hotspot.tiles.body': 'Noin {tiles} kuusikulmaista laattaa peittää toisen vaiheen tuulenpuoleisen sivun, sen puolen, joka kohtaa ilman ensimmäisenä paluussa. Jokainen on noin {tile_cm} cm leveä (arvio), ja välissä on noin {gap_mm} mm rako, jotta keraami voi laajeta kuumetessaan. Ne näyttävät mustilta pinnoitteensa vuoksi. Vastakkainen sivu on enimmäkseen paljasta ruostumatonta terästä, joten valokuvan alus näyttää luultavasti laatoitettua sivuaan. Laatat on mitoitettu kestämään noin {tile_c} °C, mikä on lähellä ruostumattoman teräksen sulamispistettä; ilman niitä runko ei selviäisi paluusta.',
  'edu.hotspot.frost.short': 'Huurre',
  'edu.hotspot.frost.title': 'Säiliöiden huurre',
  'edu.hotspot.frost.body': 'Nestemäinen happi kiehuu noin −183 °C:ssa ja nestemäinen metaani noin −162 °C:ssa. Säiliön seinä on lähes yhtä kylmä, joten kostean Meksikonlahden ilman vesihöyry jäätyy siihen: pääosin huurteena, jolloin höyry muuttuu suoraan jääkiteiksi, sekä pisaroina, jotka tiivistyvät ja jäätyvät. Ensimmäisen vaiheen alaosa, karkeasti alimmat {frost_pct} % noin {frost_h} m:n korkeuteen asti, sisältää nestemäisen hapen ja on paksuin ja kirkkain. Yläosa on tummempi ja ohuempi. Kun raketti kiihtyy ja tärisee, jäälevyjä murtuu irti ja putoaa pois.',
  'edu.hotspot.tower.short': 'Torni',
  'edu.hotspot.tower.title': 'Laukaisutorni',
  'edu.hotspot.tower.body': 'Torni on noin {tower_h} m korkea ukkosenjohdattimineen ja kantaa kahta suurta vartta, joita kutsutaan syömäpuikoiksi. Se pinoaa raketin ja ottaa palaavia ensimmäisiä vaiheita kiinni; ensimmäinen kiinniotto tehtiin lokakuussa 2024. Tässä pysäytetyssä hetkessä, {tf} s vapautuksen jälkeen, ensimmäisen vaiheen moottoritaso on juuri noussut tornin huipun ohi vain noin {v_tf_kmh} km/h nopeudella. Torni selviää laukaisusta, koska raketti nousee sen luota pois, laukaisualusta ja liekkikaivanto kääntävät pakokaasun sivulle ja vesikastelu sitoo lämpöä.',
  'edu.hotspot.chopsticks.short': 'Syömäpuikot',
  'edu.hotspot.chopsticks.title': 'Tarttumavarret',
  'edu.hotspot.chopsticks.body': 'Kaksi teräsvartta kulkee kelkassa, joka on kuvassa noin {carriage_h} m:n korkeudessa tornissa. Kumpikin varsi on noin {arm} m pitkä, ja ne ulottuvat noin {reach} m tornin sivusta (arvioita joukkoistetusta kartasta). Ne nostavat ensimmäiset ja toiset vaiheet laukaisualustalle ja sulkeutuvat palaavien ensimmäisten vaiheiden ympärille tarttuen niiden kiinniottotappeihin. Tässä ne on jätetty leveälle auki, noin {span} m kärjestä kärkeen, jotta raketti kulkee puhtaasti ohi. Riippuva puomi noin {boom_h} m:n korkeudessa on todennäköisesti huoltovarsi.',
  'edu.hotspot.olm.short': 'Laukaisualusta',
  'edu.hotspot.olm.title': 'Laukaisualusta (OLM)',
  'edu.hotspot.olm.body': 'Raketti seisoi korotetulla, vesijäähdytteisellä teräsalustalla noin {olm_h} m maanpinnan yläpuolella (arvio, julkaistua lukua ei löytynyt); moottoreiden alla oli pyöreä aukko ja kaksikymmentä pidätinkiinnitintä. Laukaisualusta 2 suunniteltiin sen jälkeen, kun ensimmäinen Starship-laukaisu sinkosi betonia kilometrien päähän. Vettä vapautetaan usealta kohdalta, ja valunta ohjataan altaaseen; heinäkuun 2026 testin kerrottiin sosiaalisessa mediassa virranneen {flow_gpm} USA:n gallonaa minuutissa, mitä ei ole vahvistettu. Alusta on noin {olm_w} m neliö, sekin arvio. Koska alusta on {olm_h} m korkealla, moottoritaso alkoi {olm_h} m:n korkeudelta.',
  'edu.hotspot.trench.short': 'Liekkikaivanto',
  'edu.hotspot.trench.title': 'Liekkikaivanto',
  'edu.hotspot.trench.body': 'Laukaisualustan alla oleva betonikaivanto, joka on vuorattu ruostumattomalla teräksellä ja jäähdytetty vedellä, ottaa pakokaasun vastaan. Sen koko on arvio: noin {tr_l} m pitkä, {tr_w} m leveä ja {tr_d} m syvä, suunnaltaan suunnilleen itä–länsi, ja sen ohjain jakaa suihkun kahdeksi virraksi. Siksi kuvan kaksi valtavaa pilveä kohoavat raketin molemmille puolille. Ilman kaivantoa pakokaasu iskeytyisi tasaiseen maahan, kaivaisi kuopan ja sinkoaisi roskia kilometrien päähän, kuten ensimmäisellä lennolla kävi.',
  'edu.hotspot.tankfarm.short': 'Säiliökenttä',
  'edu.hotspot.tankfarm.title': 'Säiliökenttä',
  'edu.hotspot.tankfarm.body': 'Muutaman sadan metrin päässä laukaisupaikasta idässä, lähimmillään noin {tank_dist} m:n etäisyydellä, on rakettia ruokkiva säiliökenttä. Kartalla siinä näkyy noin {lox_n} vaakasuoraa nestemäisen hapen ja typen säiliötä, kukin noin {lox_d} m leveä ja {lox_l} m pitkä, {ch4_n} nestemäisen metaanin säiliötä, {water_n} vesisäiliötä kasteluun ja {vap_n} höyrystintä (joukkoistettuja laskelmia). Noin {prop_total} tonnin kylmän ajoaineen lataus vie noin 45 minuuttia ennen laukaisua. Valokuvanäkymässä se on piilossa höyryn takana.',
  'edu.hotspot.plume.short': 'Pakokaasusuihku',
  'edu.hotspot.plume.title': 'Pakokaasusuihku',
  'edu.hotspot.plume.body': 'Jokaisen moottorin takana kaasu liikkuu noin {ve_km} km/s nopeudella, karkeasti kymmenkertaisena äänen nopeuteen ilmassa nähden, ja yhdistynyt liekki ulottuu tässä noin {rise_tf} m alas alustalle. Metaani palaa vähällä nokea, joten ydin hohtaa vain heikosti ja näyttää kuvassa vaalean violetinpunaiselta, aivan eri tavalla kuin petrolirakettien nokinen oranssi. Sen lämpötila suuttimen suulla on yhä noin {t_exit} K laajenemisen jälkeen, kun palotilassa se oli noin {t_chamber} K (molemmat ovat arvioita).',
  'edu.hotspot.machdiamonds.short': 'Iskuaaltokuvio',
  'edu.hotspot.machdiamonds.title': 'Iskuaaltokuvio (Machin timantit)',
  'edu.hotspot.machdiamonds.body': 'Suihku poistuu jokaisesta suuttimesta eri paineessa kuin ympäröivä ilma. Merenpinnan lähellä Raptorin ulostulopaineen arvioidaan olevan noin {exit_p} bar ulkoisen 1,01 barin sijaan, joten suihku on hieman ylilaajentunut. Vinoja iskuaaltoja syntyy suuttimen reunalla, ne risteävät suihkussa ja heijastuvat sen reunasta laajenemisaaltoina, ja kuvio toistuu suihkua pitkin. Tämä toistuva iskuaaltokuvio koostuu soluista, joita kutsutaan Machin timanteiksi; ne ovat kirkkaampia, koska kaasu niissä on puristunut ja kuumempaa. Raketin noustessa ulkoinen paine laskee ulostulopainetta pienemmäksi, suihku muuttuu alilaajentuneeksi, ja solut venyvät ja himmenevät.',
  'edu.hotspot.steam.short': 'Höyrypilvet',
  'edu.hotspot.steam.title': 'Höyrypilvet',
  'edu.hotspot.steam.body': 'Suurin osa jättipilvistä on vettä, ei savua. FAA:n suunnitteluluku on jopa noin {water_gal} USA:n gallonaa ({water_ml} miljoonaa litraa) alustalle ja kaivantoon, ja SpaceX arvioi noin {vap_pct} %:n siitä höyrystyvän vesihöyryksi, joka tiivistyy pisaroiksi viileässä kosteassa ilmassa. Pakokaasu itse lisää vähemmän: enintään noin {h2o_tps} tonnia vettä ja {co2_tps} tonnia hiilidioksidia sekunnissa. Oranssi väri tulee matalalta aamuauringolta, joka on vain {sun_alt}° horisontin yläpuolella, sekä suihkun hehkusta.',
  'edu.hotspot.fireball.short': 'Tulipallo',
  'edu.hotspot.fireball.title': 'Tulipallo pohjalla',
  'edu.hotspot.fireball.body': 'Kun suihku osuu alustaan ja kaivantoon, se kääntyy sivulle ja leviää. Pakokaasu on polttoainerikasta, seossuhde on {of} täydellisen 4,0:n sijaan, joten ylimääräinen hiilimonoksidi, vety ja metaani kohtaavat ilman ja palavat uudelleen. Tämä jälkipoltto kuumentaa kaasun, ja suurimman osan pilarin juuren kirkkaasta keltaoranssista hehkusta uskotaan tulevan kaasun mukana kulkevista pienistä kuumista hiukkasista, kuten noesta ja alustan pölystä. Se on kuumempi ja kirkkaampi kuin yllä oleva vaalea suihku, se on valaistu sisältä, ja se valaisee ympärillään olevan höyryn.',
  'edu.hotspot.soundfront.short': 'Ääniaaltorintama',
  'edu.hotspot.soundfront.title': 'Ääniaaltorintama',
  'edu.hotspot.soundfront.body': 'Ääni kulkee lämpimässä ilmassa vain noin {c} m/s nopeudella (oletuksena 25 °C). Moottorit syttyvät {lead} s ennen vapautusta, joten sytytyksen ääni on levinnyt {lead} s plus {tf} s ja on nyt noin {r_tf_km} km:n säteinen pallo. Sen sisällä melu on musertava: noin {spl100} dB 100 m:n päässä yksinkertaisen arvion mukaan ja lähellä suihkua jopa noin {near_db} dB. Lennolla 5 vuonna 2024 tutkijat mittasivat noin {spl10k} dB 10 km:n ja {spl20k} dB 20 km:n päässä. Rintaman ulkopuolella näkisit raketin selvästi ennen kuin kuulisit sen.',

  // ── selitykset ───────────────────────────────────────────────────────────────────────────
  'edu.ex.intro': 'Lyhyitä selityksiä tämän kuvan fysiikasta. Luvut päivittyvät speksistä.',
  'edu.ex.tw.title': 'Miksi työntövoima-painosuhde 1,5 tekee hitaan alun',
  'edu.ex.tw.body': 'Vapautushetkellä raketti painaa noin {w0} MN (massa × putoamiskiihtyvyys) ja moottorit työntävät {thrust} MN:llä. Vain erotus kiihdyttää: a = g × (T/W − 1) = 9,8 × ({tw0} − 1) = {a0} m/s², noin {g_net0} g.\n\nMatkustaja tuntisi {g0_load} g, koska istuimen täytyy sekä kannatella häntä että kiihdyttää häntä, joten se työntää {g0_load}-kertaisella painolla. Matka kasvaa suunnilleen kuten ½ a t², joten {rise_tf} m kestää noin {tf} s, ja nopeus on vain {v_tf} m/s ({v_tf_kmh} km/h). Raketti kevenee {mdot} tonnia sekunnissa, joten kiihtyvyys jatkaa kasvamistaan.',
  'edu.ex.tw.cap': 'Voimat vapautuksessa; maa painaa vastaan nousuun asti.',
  'edu.ex.tw.slider': 'Lähtömassa',
  'edu.ex.tw.result': 'Massalla {m} t moottoritaso saavuttaa pysäytyskorkeuden hetkellä T+{tf} s nopeudella {v} m/s, ja työntövoima-painosuhde on vapautuksessa {tw}.',
  'edu.ex.isp.title': 'Työntövoima liikemäärästä ja mitä Isp tarkoittaa',
  'edu.ex.isp.body': 'Raketti työntää, koska se heittää massaa taaksepäin. Työntövoima on liikemäärävirta plus painetermi, F = ṁ × v_suihku + (pₑ − pₐ) × Aₑ. Insinöörit niputtavat molemmat yhdeksi efektiiviseksi suihkunopeudeksi vₑ = Isp × g₀ = {isp} s × 9,81 m/s² = {ve} m/s. Kun {mdot} tonnia sekunnissa poistuu, tulos on {thrust} MN. Isp on kuin polttoaineenkulutusluku: sekunteja työntövoimaa ajoaineen painoyksikköä kohti.\n\nPainetermi on tässä pieni. {alt_tf} m:n korkeudessa työntövoima on kasvanut vain {gain_tf} %. Tyhjiössä tämä malli lisäisi {gain_vac} %, noin {thrust_vac} MN:iin.',
  'edu.ex.isp.cap': 'Massavirta kertaa suihkunopeus on työntövoima.',
  'edu.ex.rocketeq.title': 'Rakettiyhtälö',
  'edu.ex.rocketeq.body': 'Tsiolkovskin rakettiyhtälö sanoo, että raketin saama nopeus on Δv = vₑ × ln(m₀ / m₁). Kun vₑ = {ve_km} km/s, alkumassa on {m0} t ja jäljellä on noin {m_meco} t ensimmäisen vaiheen moottoreiden sammuessa (massasuhde {mass_ratio}), ihanteellinen Δv on {dv_ideal} km/s. Loppumassa olettaa täyden virtauksen {t_meco} sekunnin ajan.\n\nPainovoima ja ilmanvastus vievät suuren osan, joten todellinen nopeus vaiheiden irrotuksessa on vain noin {dv_meco} km/s (arvio). Siksi raketit vaiheistetaan: tyhjän ensimmäisen vaiheen pudottaminen estää kuljettamasta sen kuivamassaa aina kiertoradalle.',
  'edu.ex.rocketeq.cap': 'Massasuhde ratkaisee, kuinka paljon nopeutta ajoaine voi ostaa.',
  'edu.ex.steam.title': 'Miksi pilvet ovat valkoisia ja oranssin valaisemia',
  'edu.ex.steam.body': '{steam_t} tonnin veden muuttaminen höyryksi vaatii noin {vap_tj} TJ, minkä suihkun {chem_gw} GW:n kemiallinen teho voisi tuottaa vain noin {vap_s} sekunnissa. Höyry kohtaa viileän kostean ilman ja tiivistyy pisaroiksi, joiden läpimitta on muutamasta kymmeniin mikrometreihin. Valon aallonpituutta selvästi suuremmat pisarat sirottavat kaikkia värejä lähes yhtä paljon (Mie-sironta), joten pilvi näyttää valkoiselta. Se ei ole savua.\n\nNoin {sun_alt}° horisontin yläpuolella aurinko paistaa paksun ilmakerroksen läpi, joka poistaa sinistä. Pilvet ottavat vastaan tuon oranssin valon, ja suihku lisää alhaalta oman hehkunsa.',
  'edu.ex.steam.cap': 'Pilvipisaroiden Mie-sironta on lähes värisokeaa.',
  'edu.ex.diamonds.title': 'Ylilaajentuneet suuttimet ja iskuaaltokuvio (Machin timantit)',
  'edu.ex.diamonds.body': 'Se, onko suihku ylilaajentunut vai alilaajentunut, riippuu sen ulostulopaineesta suhteessa ulkoilmaan. Tässä ulostulopaineen arvioidaan olevan noin {exit_p} bar ja ilma on 1,01 bar, joten suihku on ylilaajentunut: vinot iskuaallot suuttimen reunalla puristavat sitä, se ylittää tasapainon ja laajenemisaalto vapauttaa sen. Jokainen puristus ja vapautus tekee yhden kirkkaan solun.\n\nUlkoinen paine laskee raketin noustessa, ja noin {match_km} km:n yläpuolella se on ulostulopainetta pienempi, jolloin suihku muuttuu alilaajentuneeksi ja solut pitenevät ja himmenevät. Laukaisualustan lähellä 33 moottorin kuviot menevät päällekkäin, joten yksittäisiä timantteja on vaikea erottaa.',
  'edu.ex.diamonds.cap': 'Iskuaallot ja laajenemiset toistuvat suihkua pitkin.',
  'edu.ex.colour.title': 'Suihkun väri ja jälkipoltto',
  'edu.ex.colour.body': 'Moottorit käyvät polttoainerikkaina (hapen ja polttoaineen suhde {of} täydellisen 4,0:n sijaan), ja metaani tekee vain vähän nokea. Siksi ydin hehkuu vain heikosti. Sen violetinpunainen sävy tulee viritettyjen CH- ja CO₂-molekyylien sinisestä säteilystä sekä kirkkaista iskuaaltosoluista, ja kameran värisävy korostaa sitä.\n\nSiellä, missä ylimääräinen hiilimonoksidi, vety ja metaani sekoittuvat ilmaan, ne palavat uudelleen. Jälkipoltto kuumentaa kaasun ja sen mukana kulkevat hiukkaset (noki, pöly), ja kuumat hiukkaset hehkuvat keltaoranssina kuin liekki. Kuuma vesihöyry ja hiilidioksidi säteilevät enimmäkseen infrapunaa, jota emme näe. Pilarin juuren maahehku on tätä jälkipolttoa sekä sisältä valaistua höyryä.',
  'edu.ex.colour.cap': 'Ydin: vaalean violetti. Sekoittumisvyöhyke: keltaoranssi.',
  'edu.ex.sound.title': 'Ääniaaltorintama',
  'edu.ex.sound.body': 'Hetkellä t lähtenyt ääni saavuttaa etäisyyden r hetkellä t + r/c. Moottorit syttyivät {lead} s ennen vapautusta, joten sytytyksen äänen rintaman säde on c × (t + {lead} s) = {c} m/s × ({tf} + {lead}) s = {r_tf_km} km.\n\nLähteen äänitehotaso on noin {lw} dB. Se on arvio, joka olettaa {eff_pct} %:n suihkun {jet_gw} GW:n tehosta muuttuvan ääneksi (NASAn nyrkkisääntö on 0,2–0,8 %). Yksinkertainen vaimeneminen ennustaa 10 km:n päähän {spl_free10k} dB, mutta lennolla 5 tehty mittaus antoi {spl10k} dB. Suihku säteilee suurimman osan äänestään vinosti eikä tasaisesti, kasteluvesi ja alusta ottavat osan, ja ilma, maa ja sää vaimentavat loput. Kaavio näyttää molemmat käyrät.',
  'edu.ex.sound.cap': 'Äänenvoimakkuus etäisyyden funktiona, malli ja mittaus.',
  'edu.ex.staging.title': 'Max-Q ja aktiivinen vaiheiden irrotus',
  'edu.ex.staging.body': 'Dynaaminen paine, q = ½ ρ v², on ilman aiheuttama kuormitus raketille. Se kasvaa nopeuden mukana ja laskee sitten ilman ohentuessa, joten se huipentuu noin minuutin kuluttua noususta (lennolla 14 noin hetkellä T+{t_maxq} s). Yksinkertainen pystysuora malli antaa noin {maxq_kpa} kPa, mikä on vain suuruusluokan arvio. Moottorit yleensä kuristuvat tämän huipun kohdalla kuormien pienentämiseksi.\n\nNoin hetkellä T+{t_meco} s ensimmäinen vaihe sammuttaa suurimman osan moottoreistaan, toinen vaihe sytyttää omansa vielä kiinni ollessaan, ja vaiheet irtoavat noin hetkellä T+{t_stage} s: aktiivinen vaiheiden irrotus (hot staging).',
  'edu.ex.staging.cap': 'Tapahtumat ensimmäisten {t_stage} sekunnin aikana.',
  'edu.ex.catch.title': 'Tornin kiinniotto',
  'edu.ex.catch.body': 'Laskeutumisjalkojen sijaan ensimmäinen vaihe palaa tornille ja tarttumavarret sulkeutuvat sen ympärille pitäen sitä kiinni {pins} kiinniottotapista lähellä yläpäätä, noin {pin_h} m:n korkeudessa. Ilman jalkoja kannettavana ensimmäinen vaihe on kevyempi, ja se voidaan nostaa suoraan takaisin laukaisualustalle uutta lentoa varten.\n\nKiinniotto vaatii tarkkuutta metrin murto-osiin. Ensimmäisiä vaiheita on otettu kiinni lennosta 5 (lokakuu 2024) lähtien. Jos kuva on lennolta 14, ensimmäinen vaihe teki sen sijaan laskeutumispolton ja hallitun vesillelaskun Meksikonlahteen, eikä toista vaihetta ollut siihen mennessä otettu kiinni.',
  'edu.ex.catch.cap': 'Tapit ensimmäisessä vaiheessa, varret tornissa.',
  'edu.ex.frost.title': 'Miksi raketti on huurteinen',
  'edu.ex.frost.body': 'Nestemäinen happi kiehuu noin −183 °C:ssa ja nestemäinen metaani noin −162 °C:ssa. Teräksinen säiliön seinä on lähes yhtä kylmä, joten kostean Meksikonlahden ilman vesihöyry jäätyy siihen, pääosin huurteena (höyry muuttuu suoraan jääksi) sekä tiivistyneinä pisaroina, jotka jäätyvät. Huurteisen happisäiliön ja ohuemman metaanisäiliön raja on kuvassa noin {frost_h} m:n korkeudella.\n\nHuurre on hyödyllinen vihje: se näyttää, missä kylmä neste on. Se myös murtuu ja irtoaa hiutaleina, kun raketti tärisee ja kiihtyy.',
  'edu.ex.frost.cap': 'Vesihöyry jäätyy kylmään säiliön seinään.',
  'edu.ex.heat.title': 'Lämpösäteily',
  'edu.ex.heat.body': 'Suihku hehkuu, joten se säteilee lämpöä äänen lisäksi. Karkea suuruusluokka-arvio antaa noin {q100} kW/m² 100 m:n päässä, noin {q100} kertaa täyden auringonvalon voimakkuus, ja vain {q1k} kW/m² 1 km:n päässä, vähemmän kuin auringonvalo (noin 1 kW/m²). Vuo pienenee etäisyyden neliössä, eikä arviossa ole huomioitu höyryä eikä ilman absorptiota.\n\nEnergia tulee noin {chem_gw} GW:n kemiallisesta tehosta, mikä vastaa noin {chem_gw} ison, 1 GW:n voimalaitoksen tehoa. Se on yksi syy siihen, että alue tyhjennetään kilometrien säteeltä, melun ja sinkoavien roskien ohella; kaukaiset katsojat tuntevat vain hetkellisen hehkun.',
  'edu.ex.heat.cap': 'Lämpösäteilyn käänteinen neliölaki.',
  'edu.ex.fuel.title': 'Metaani ja happi',
  'edu.ex.fuel.body': 'Raptor polttaa nestemäistä metaania nestemäisellä hapella massasuhteella {of} : 1, mikä on polttoainerikasta täydelliseen 4,0:aan verrattuna. Metaani on halpaa, palaa petrolia puhtaammin ja sitä voi valmistaa Marsissa hiilidioksidista ja vedestä.\n\nNoin {mdot_lox} tonnia happea ja {mdot_ch4} tonnia metaania kuluu sekunnissa, joten {prop_b} tonnia riittäisi täydellä työntövoimalla noin {burn_s} sekunniksi. Todellinen moottorien sammutus on noin hetkellä T+{t_meco} s, mikä jättäisi noin {reserve} tonnia paluupolttoon ja laskeutumiseen; todellisia virtausarvoja ja kuristusta ei ole julkaistu, joten tämä on vain tarkistus.',
  'edu.ex.fuel.cap': 'Hapen ja metaanin massavirta.',
  'edu.dia.weight': 'Paino',
  'edu.dia.thrust': 'Työntö',
  'edu.dia.net': 'Netto',
  'edu.dia.ground': 'maa',
  'edu.dia.nozzle': 'suutin',
  'edu.dia.shock': 'iskuaalto',
  'edu.dia.expansion': 'laajeneminen',
  'edu.dia.core': 'ydin',
  'edu.dia.mix': 'sekoittumisvyöhyke',
  'edu.dia.pad': 'alusta',
  'edu.dia.ignition': 'sytytys',
  'edu.dia.now': 'nyt',
  'edu.dia.free': 'vapaan kentän malli',
  'edu.dia.measured': 'mitattu',
  'edu.dia.booster': 'ensimmäinen vaihe',
  'edu.dia.ship': 'toinen vaihe',
  'edu.dia.arm': 'varsi',
  'edu.dia.pin': 'tappi',
  'edu.dia.lox': 'nestehappi',
  'edu.dia.ch4': 'metaani',
  'edu.dia.frost': 'huurre',
  'edu.dia.km': 'km',
  'edu.dia.steam': 'höyry',
  'edu.dia.droplets': 'pisarat',
  'edu.dia.sun': 'matala aurinko',
  'edu.dia.maxq': 'max-Q',
  'edu.dia.meco': 'MECO',
  'edu.dia.stage': 'irrotus',
  'edu.dia.heat': 'lämpövuo',
  'edu.dia.sunlevel': 'auringonvalo',
  'edu.dia.oxygen': 'happi',
  'edu.dia.methane': 'metaani',
  'edu.dia.burn': 'poltto',
  'edu.dia.thrustlabel': 'työntö',

  // ── speksiavainten nimet ─────────────────────────────────────────────────────────────────
  'edu.k.booster_height_m': 'Ensimmäisen vaiheen korkeus', 'edu.k.stack_height_m': 'Pinon korkeus', 'edu.k.ship_height_m': 'Toisen vaiheen korkeus',
  'edu.k.diameter_m': 'Halkaisija', 'edu.k.booster_engines': 'Ensimmäisen vaiheen moottorit', 'edu.k.ship_engines': 'Toisen vaiheen moottorit',
  'edu.k.booster_prop_mass_b3_t': 'Ensimmäisen vaiheen ajoaine', 'edu.k.ship_prop_mass_b3_t': 'Toisen vaiheen ajoaine',
  'edu.k.booster_dry_mass_b3_t': 'Ensimmäisen vaiheen kuivamassa', 'edu.k.ship_dry_mass_b3_t': 'Toisen vaiheen kuivamassa', 'edu.k.payload_mass_f14_t': 'Hyötykuorma',
  'edu.k.liftoff_mass_used_t': 'Lähtömassa', 'edu.k.liftoff_mass_published_t': 'Lähtömassa, yksi katsaus', 'edu.k.liftoff_mass_sum_of_parts_t': 'Lähtömassa, osien summa',
  'edu.k.liftoff_thrust_b3_MN': 'Työntövoima lähdössä', 'edu.k.liftoff_thrust_b3_Mlbf': 'Työntövoima lähdössä (paunavoima)',
  'edu.k.liftoff_tw_central': 'Työntövoima / paino vapautuksessa', 'edu.k.liftoff_tw_range_low': 'Työntövoima / paino, alaraja', 'edu.k.liftoff_tw_range_high': 'Työntövoima / paino, yläraja',
  'edu.k.raptor3_thrust_sl_tf': 'Raptor 3:n työntövoima merenpinnalla', 'edu.k.raptor3_thrust_sl_alt_tf': 'Raptor 3:n työntövoima, lehdistön luku',
  'edu.k.raptor3_chamber_pressure_bar': 'Palotilan paine', 'edu.k.raptor3_chamber_pressure_alt_bar': 'Palotilan paine, vaihtoehtoinen',
  'edu.k.raptor3_engine_mass_kg': 'Moottorin massa', 'edu.k.raptor_of_ratio': 'Hapen ja polttoaineen suhde',
  'edu.k.raptor3_isp_sl_used_s': 'Ominaisimpulssi merenpinnalla', 'edu.k.raptor3_isp_vac_s': 'Ominaisimpulssi tyhjiössä',
  'edu.k.raptor_exhaust_velocity_sl_mps': 'Suihkunopeus', 'edu.k.raptor_chamber_temperature_K': 'Palotilan lämpötila',
  'edu.k.raptor_exit_static_temperature_K': 'Suuttimen suun lämpötila', 'edu.k.raptor_exit_pressure_bar': 'Suuttimen suun paine',
  'edu.k.raptor_exit_mach': 'Ulostulon Machin luku', 'edu.k.raptor_nozzle_exit_diameter_m': 'Suuttimen suun halkaisija',
  'edu.k.raptor_nozzle_expansion_ratio': 'Suuttimen laajenemissuhde',
  'edu.k.mdot_booster_total_kgps': 'Ajoainevirta, ensimmäinen vaihe', 'edu.k.mdot_lox_total_kgps': 'Happivirta', 'edu.k.mdot_ch4_total_kgps': 'Metaanivirta',
  'edu.k.booster_full_thrust_burn_time_s': 'Polttoaika täydellä työntövoimalla', 'edu.k.jet_mechanical_power_GW': 'Suihkun teho', 'edu.k.chemical_power_GW': 'Kemiallinen teho',
  'edu.k.vac_thrust_booster_MN': 'Työntövoima tyhjiössä', 'edu.k.thrust_gain_150m_pct': 'Työntövoiman kasvu 150 m:ssä', 'edu.k.engine_start_lead_s': 'Sytytys ennen vapautusta',
  'edu.k.tower_height_used_m': 'Tornin korkeus', 'edu.k.olm_height_m': 'Laukaisualustan korkeus', 'edu.k.base_rise_to_tower_top_m': 'Nousu tornin huipulle',
  'edu.k.t_base_at_tower_top_s': 'Aika tornin huipulle', 'edu.k.v_base_at_tower_top_mps': 'Nopeus tornin huipulla', 'edu.k.a_net_at_tower_top_mps2': 'Kokonaiskiihtyvyys siinä',
  'edu.k.max_q_time_f14_s': 'Max-Q:n ajankohta', 'edu.k.max_q_model_kPa': 'Max-Q, yksinkertainen malli', 'edu.k.meco_time_f14_s': 'Päämoottorien sammutus (MECO)',
  'edu.k.hot_staging_time_f14_s': 'Aktiivinen vaiheiden irrotus', 'edu.k.meco_alt_est_km': 'Korkeus sammutushetkellä', 'edu.k.meco_speed_est_mps': 'Nopeus sammutushetkellä',
  'edu.k.deluge_water_pad1_gal': 'Kastelivesi (alusta 1)', 'edu.k.deluge_water_pad1_kg': 'Kasteluveden massa', 'edu.k.deluge_vaporised_fraction': 'Höyrystyvä osuus',
  'edu.k.deluge_pad2_test_flow_gpm': 'Alustan 2 testivirtaus', 'edu.k.deluge_pad2_test_flow_m3ps': 'Alustan 2 testivirtaus',
  'edu.k.deluge_vaporisation_energy_J': 'Veden höyrystämiseen tarvittava energia', 'edu.k.combustion_h2o_tps': 'Palamisen tuottama vesi', 'edu.k.combustion_co2_tps': 'Palamisen tuottama hiilidioksidi',
  'edu.k.launch_table_mass_pad1_t': 'Laukaisupöydän massa (alusta 1)',
  'edu.k.sound_speed_25C_mps': 'Äänen nopeus, 25 °C', 'edu.k.sound_front_radius_at_photo_m': 'Ääniaaltorintaman säde, arvio', 'edu.k.acoustic_eff_central': 'Akustinen hyötysuhde',
  'edu.k.sound_power_level_dB': 'Äänitehotaso', 'edu.k.spl_100m_dB': 'Äänenvoimakkuus 100 m:n päässä', 'edu.k.spl_1km_dB': 'Äänenvoimakkuus 1 km:n päässä',
  'edu.k.spl_10km_measured_dB': 'Äänenvoimakkuus 10 km:n päässä, mitattu', 'edu.k.spl_20km_measured_dB': 'Äänenvoimakkuus 20 km:n päässä, mitattu',
  'edu.k.near_field_dB': 'Lähikentän äänenvoimakkuus', 'edu.k.faa_lmax_contour_dB': 'FAA:n melukäyrä',
  'edu.k.plume_radiant_flux_100m_kWm2': 'Lämpösäteily 100 m:n päässä', 'edu.k.plume_radiant_flux_1km_kWm2': 'Lämpösäteily 1 km:n päässä',
  'edu.k.vehicle.ship.tile.count_windward': 'Laattoja tuulenpuolella', 'edu.k.vehicle.ship.tile.hex_size': 'Laatan leveys', 'edu.k.vehicle.ship.tile.gap': 'Laattojen rako',
  'edu.k.vehicle.booster.grid_fin.count': 'Ritiläevät', 'edu.k.vehicle.booster.grid_fin.scale_vs_v2': 'Ritiläevien koko V2:een verrattuna', 'edu.k.vehicle.booster.grid_fin.span': 'Ritiläevän jänneväli',
  'edu.k.vehicle.booster.hot_stage_vent_count': 'Irrotusrenkaan aukot', 'edu.k.vehicle.booster.catch_pin_count': 'Kiinniottotapit', 'edu.k.vehicle.booster.catch_pin_height': 'Kiinniottotappien korkeus',
  'edu.k.vehicle.photo.frost_boundary_height': 'Huurteen rajan korkeus', 'edu.k.vehicle.booster.frost.lox_tank_fraction_of_height': 'Huurteinen osuus ensimmäisestä vaiheesta',
  'edu.k.vehicle.booster.common_dome_height': 'Yhteisen välipohjan korkeus', 'edu.k.vehicle.ship.aft_flap.count': 'Takasiivekkeet', 'edu.k.vehicle.ship.forward_flap.count': 'Etusiivekkeet',
  'edu.k.pad.tower2_height': 'Tornin korkeus', 'edu.k.pad.chopstick_carriage_height_in_photo': 'Kelkan korkeus kuvassa', 'edu.k.pad.chopstick_open_span_photo': 'Varret auki, kärjestä kärkeen',
  'edu.k.pad.chopstick_arm_length': 'Varren pituus', 'edu.k.pad.chopstick_reach_from_tower_face': 'Ulottuma tornista', 'edu.k.pad.qd_arm_boom_height_in_photo': 'Puomin korkeus',
  'edu.k.pad.vaporizers': 'Höyrystimet', 'edu.k.pad.coast_distance_east': 'Etäisyys rannikolle',
  'edu.k.scene.t_freeze': 'Pysäytetty hetki', 'edu.k.scene.vehicle_base_height': 'Moottoritason korkeus', 'edu.k.scene.olm_deck_height': 'Laukaisualustan kansi', 'edu.k.scene.sun_altitude': 'Auringon korkeus',
};
