// English strings for the educational mode. {name} placeholders are filled LIVE from the spec and
// the liftoff model by src/edu/vars.ts (so every number in the prose follows specs/starship.json).
// Hotspot bodies are 60-120 words (checked by tests/physics.test.ts). Explainer paragraphs are
// separated by a blank line. Finnish counterpart: content.fi.ts (same keys).

export const en: Record<string, string> = {
  // ── shell ────────────────────────────────────────────────────────────────────────────────
  'edu.title': 'Educational mode',
  'edu.panel.title': 'Physics of this moment',
  'edu.panel.aria': 'Physics of this moment: numbers, charts, explainers and sources',
  'edu.tab.moment': 'Moment',
  'edu.tab.explain': 'Explainers',
  'edu.tab.sources': 'Sources',
  'edu.collapse': 'Hide panel',
  'edu.expand': 'Show panel',
  'edu.close': 'Close',
  'edu.exit': 'Leave educational mode',
  'edu.pill': 'Physics of this moment',
  'edu.markers.aria': 'Hotspots. Choose one to read about it.',
  'edu.marker.open': 'Open the card for {title}',
  'edu.cat.vehicle': 'Vehicle',
  'edu.cat.pad': 'Launch site',
  'edu.cat.fx': 'Plume and clouds',
  'edu.cat.physics': 'Physics',
  'edu.badge.src': 'sourced',
  'edu.badge.est': 'estimate',
  'edu.badge.model': 'model',
  'edu.badge.src.tip': 'Sourced value. Opens the source in a new tab.',
  'edu.badge.est.tip': 'Estimate: {note}',
  'edu.badge.model.tip': 'Computed by the liftoff model from spec values.',
  'edu.differs.mass': 'Sources differ: {m0_pub} t published, {m0_sum} t summing the parts. The midpoint is used.',
  'edu.differs.thrust': 'Sources differ: some quote {raptor_tf_alt} tf. {raptor_tf} tf matches the published {thrust} MN total.',
  'edu.differs.pc': 'Sources differ: {pc} bar or {pc_alt} bar. The lower figure is used.',
  'edu.differs.isp': 'Sources differ: 330 s or 350 s for sea level. The lower figure is used.',
  'edu.differs.label': 'sources differ',
  'edu.card.keynums': 'Key numbers',
  'edu.card.flyto': 'Fly to this',
  'edu.card.close': 'Close card',
  'edu.card.aria': 'Details: {title}',

  // ── moment tab ───────────────────────────────────────────────────────────────────────────
  'edu.layers': 'Overlays',
  'edu.layer.forces': 'Force arrows',
  'edu.layer.sound': 'Sound front',
  'edu.moment.intro': 'The picture is frozen {tf} s after release, when the engine plane is {alt_tf} m above the ground. These numbers are computed for exactly that instant.',
  'edu.tile.time': 'Time after release',
  'edu.tile.alt': 'Engine-plane altitude',
  'edu.tile.vel': 'Velocity',
  'edu.tile.acc': 'Net acceleration',
  'edu.tile.tw': 'Thrust / weight',
  'edu.tile.mass': 'Mass',
  'edu.tile.burned': 'Propellant burned',
  'edu.tile.mdot': 'Mass flow',
  'edu.tile.ve': 'Exhaust velocity',
  'edu.tile.thrust': 'Thrust',
  'edu.tile.vel.sub': '{kmh} km/h',
  'edu.tile.acc.sub': '{g} g felt aboard',
  'edu.tile.tw.sub': 'at release {tw0}',
  'edu.tile.mass.sub': 'at release {m0} t',
  'edu.tile.burned.sub': 'so far since ignition',
  'edu.tile.mdot.sub': 'oxygen {lox} + methane {ch4}',
  'edu.tile.ve.sub': 'Isp {isp} s',
  'edu.tile.thrust.sub': 'weight {weight} MN',
  'edu.tile.alt.sub': '{rise} m above the mount',
  'edu.tile.time.sub': 'ignition was T−{lead} s',
  'edu.unit.s': 's',
  'edu.chart.title': 'The first minute',
  'edu.chart.hint': 'Point at a chart to read any moment. The orange line is this frozen instant.',
  'edu.chart.alt': 'Altitude',
  'edu.chart.vel': 'Velocity',
  'edu.chart.acc': 'Net acceleration',
  'edu.chart.mass': 'Mass',
  'edu.chart.note': 'One-dimensional vertical-ascent model. The throttle-down after T+{bucket} s is a placeholder, not SpaceX data, so read the right-hand side as illustrative.',
  'edu.chart.table': 'Table view',
  'edu.chart.aria': '{name} against time after release, 0 to 60 seconds. At the frozen instant it is {value}.',
  'edu.chart.freeze': 'now',
  'edu.chart.col.t': 'T+ (s)',
  'edu.chart.col.alt': 'Altitude (m)',
  'edu.chart.col.vel': 'Velocity (m/s)',
  'edu.chart.col.acc': 'Accel. (m/s²)',
  'edu.chart.col.mass': 'Mass (t)',

  // ── force vectors and sound front (3D labels) ────────────────────────────────────────────
  'edu.force.thrust': 'Thrust',
  'edu.force.weight': 'Weight',
  'edu.force.net': 'Net force',
  'edu.force.com': 'Centre of mass (est.)',
  'edu.force.plane': 'Engine plane',
  'edu.force.scale': 'Arrow length: 1 MN = 1 m. Thrust and weight are drawn side by side for clarity; both really act along the axis.',
  'edu.force.ratio': '{ratio} × weight',
  'edu.sound.label': 'Sound front, {r} km',
  'edu.sound.sub': 'sound of ignition, made {lead} s before release',

  // ── walk HUD ─────────────────────────────────────────────────────────────────────────────
  'edu.hud.title': 'Where you stand',
  'edu.hud.dist': 'Distance to the vehicle',
  'edu.hud.ground': 'Distance to the pad',
  'edu.hud.reached': 'The sound has reached you',
  'edu.hud.reached.sub': 'Ignition sound arrived at T{t} s, before the frozen instant.',
  'edu.hud.notyet': 'The sound has not reached you yet',
  'edu.hud.notyet.sub': 'It arrives in {s} s, at T+{t} s. You are seeing the rocket before you can hear it.',
  'edu.hud.spl': 'Loudness at this spot',
  'edu.hud.spl.pending': 'Loudness when it arrives',
  'edu.hud.band.faint': 'faint',
  'edu.hud.band.loud': 'loud',
  'edu.hud.band.painful': 'painful',
  'edu.hud.band.damaging': 'damages hearing at once',
  'edu.hud.band.extreme': 'beyond anything a person can stand',
  'edu.hud.heat': 'Radiant heat',
  'edu.hud.heat.sun': '{x} × sunlight',
  'edu.hud.heat.less': 'less than sunlight',
  'edu.hud.est': 'Estimates: free-field spreading blended toward measured far-field levels; inverse-square heat.',
  'edu.hud.aria': 'Walk readout',

  // ── sources tab ──────────────────────────────────────────────────────────────────────────
  'edu.src.intro': 'Every number in this mode is read from one spec file. Values with a link are sourced. Values marked estimate are reasoned, and the note says how.',
  'edu.src.flight.title': 'Which flight is this?',
  'edu.src.flight.body': 'Flight 14 (Booster 21 / Ship 41, Block 3, Starbase Pad 2, liftoff 2026-09-28 12:48:59 UTC), about 85 % sure. It is inferred from the lighting and timing: low warm sun from the east about 35 minutes after sunrise, the Pad 2 tower, V3 proportions, and a photo posted the same day. It is not read from a caption, and the original post was not found. Flights 12 and 13 used the same pad and hardware but flew in the afternoon.',
  'edu.src.decisions.title': 'Where the research disagreed',
  'edu.src.dec.thrust': 'Raptor 3 thrust: 250 tf chosen over the 280 tf press figure, because 33 × 250 tf gives the published 80.8 MN.',
  'edu.src.dec.mass': 'Liftoff mass: 5,400 t chosen between the published 5,300 t and the 5,700 t sum of parts. The frozen moment moves by only about half a second either way.',
  'edu.src.dec.tower': 'Tower height: 144.5 m from OpenStreetMap and the FAA filing, over a 130 m guess from the photo.',
  'edu.src.dec.sun': 'Sun: altitude and azimuth were computed for the pad and time, not taken from the estimates in the notes.',
  'edu.src.dec.height': 'Booster height in the photo: 158 m, recomputed with the calibrated camera (earlier guesses were 140 and 160 m).',
  'edu.src.dec.ship': 'Ship length: 52.1 m (stack minus booster), over the 61 m listed by one page.',
  'edu.src.dec.freeze': 'Freeze time: 7.2 s in the spec. The liftoff model recomputes it from the physics; the test that checks it allows 0.3 s.',
  'edu.src.model.title': 'How the liftoff model works',
  'edu.src.model.body': 'A vertical point-mass model integrated with a fourth-order Runge–Kutta step of 0.01 s from release at full thrust. Thrust is mass flow × exhaust velocity plus a small pressure term that grows as the air thins. Drag uses Cd 0.8 in an exponential atmosphere, and gravity falls slowly with height. It starts on the {olm_h} m launch mount. The gravity-turn kick after T+10 s and the throttle-down after T+{bucket} s are not measured, so only the first ten seconds are firm.',
  'edu.src.values.title': 'Values shown in this mode',
  'edu.src.col.value': 'Value',
  'edu.src.col.status': 'Status',
  'edu.src.model.note': 'Computed by the liftoff model from these inputs.',
  'edu.src.open': 'Open source',

  // ── hotspot cards ────────────────────────────────────────────────────────────────────────
  'edu.hotspot.booster.short': 'Booster',
  'edu.hotspot.booster.title': 'Super Heavy, the first stage',
  'edu.hotspot.booster.body': 'Super Heavy is the first stage (the booster): {h_booster} m tall and {dia} m wide, built from stainless steel rings. Its {n_eng} Raptor engines burn about {mdot} tonnes of propellant every second, and the tanks hold roughly {prop_b} tonnes of liquid oxygen and liquid methane, about two thirds of the whole stack\'s mass at release. It is designed to fly back and be caught by the tower, so it can be reused instead of thrown away. Even in this frozen instant most of what you see is tank: the frosted lower part holds the liquid oxygen.',
  'edu.hotspot.ship.short': 'Ship',
  'edu.hotspot.ship.title': 'Starship, the second stage',
  'edu.hotspot.ship.body': 'The black upper part is Starship itself, the second stage. It has {n_ship_eng} Raptor engines: three at sea level and three optimised for vacuum. Its windward side is covered with about {tiles} heat-shield tiles so it can survive re-entry at orbital speed. In Block 3 it carries about {prop_s} tonnes of propellant, plus 26 Starlink V3 satellites (an estimated {payload} tonnes) on this flight. Right now it is only a passenger: its own engines will not light until hot staging at T+{t_stage} s.',
  'edu.hotspot.raptors.short': '33 Raptors',
  'edu.hotspot.raptors.title': '33 Raptor engines',
  'edu.hotspot.raptors.body': 'Each Raptor 3 makes about {raptor_tf} tonnes-force at sea level (some sources say {raptor_tf_alt}) from a combustion chamber at {pc} bar, more than 300 times atmospheric pressure. Methane and oxygen burn in a full-flow staged-combustion cycle, so no propellant is wasted on a separate turbine exhaust. All {n_eng} together give {thrust} MN, about {thrust_Mlbf} million pounds-force, making this the most powerful rocket ever flown. Twenty outer engines are fixed; the thirteen inner ones swivel (gimbal) to steer the vehicle.',
  'edu.hotspot.gridfins.short': 'Grid fins',
  'edu.hotspot.gridfins.title': 'Grid fins',
  'edu.hotspot.gridfins.body': 'Near the top of the booster sit {fins} lattice panels, about {fin_scale} times larger than on the earlier V2 booster, which had four. They are folded and passive while the engines burn on the way up. After the ship separates they steer the booster back down, working with the engine gimbals like the controls of a falling rocket. They are also strong points near the catch pins. At this resolution the fins cannot be seen in the photograph, so their position and size here are estimates.',
  'edu.hotspot.hotstage.short': 'Hot staging',
  'edu.hotspot.hotstage.title': 'The hot-staging ring',
  'edu.hotspot.hotstage.body': 'Between booster and ship sits a ventilated ring with about {vents} vents. At T+{t_meco} s the booster shuts down most of its engines. The ship then lights its own while the two are still joined, and they separate at T+{t_stage} s. The ship\'s exhaust blows through the vents of the ring. Lighting the upper stage early leaves no gap without thrust and saves a separate separation motor. On this flight it happens at roughly {meco_alt} km altitude, which is an estimate.',
  'edu.hotspot.flaps.short': 'Flaps',
  'edu.hotspot.flaps.title': 'The ship\'s flaps',
  'edu.hotspot.flaps.body': 'The ship has {n_aft_flaps} large flaps near its engines, about {aft_w} by {aft_h} m, and {n_fwd_flaps} smaller ones near the nose, about {fwd_w} by {fwd_h} m (all sizes are estimates). On the way up they are folded flat against the hull and are just along for the ride. During re-entry they are the ship\'s steering. It falls belly-first like a skydiver, and the flaps move to hold that pose and to steer, before the engines flip it upright for landing.',
  'edu.hotspot.tiles.short': 'Heat tiles',
  'edu.hotspot.tiles.title': 'Heat-shield tiles',
  'edu.hotspot.tiles.body': 'About {tiles} hexagonal tiles cover the windward half of the ship, the side that meets the air first on re-entry. Each is about {tile_cm} cm across, with a gap of about {gap_mm} mm so the ceramic can expand when hot. They look black because of their coating. The leeward side is left as bare stainless steel, which is why the ship in the photo is dark: you are looking at the tiled side. Re-entry heats the surface far beyond the melting point of steel.',
  'edu.hotspot.frost.short': 'Frost',
  'edu.hotspot.frost.title': 'Frost on the tanks',
  'edu.hotspot.frost.body': 'Liquid oxygen is at about −183 °C and liquid methane about −162 °C. Humid Gulf air touching the cold tank wall condenses and freezes into a white coat of frost and ice. The lower part of the booster, roughly the bottom {frost_pct} % below about {frost_h} m, holds the liquid oxygen and is the thickest and brightest. The upper part is darker and thinner. As the rocket accelerates and vibrates, sheets of ice crack off and fall away.',
  'edu.hotspot.tower.short': 'Tower',
  'edu.hotspot.tower.title': 'The launch tower',
  'edu.hotspot.tower.body': 'The tower is about {tower_h} m tall, including its lightning masts, and carries the two large arms called chopsticks. It stacks the rocket and, in the future, catches it. In this frozen instant, {tf} s after release, the booster\'s engine plane has just climbed past the tower top, moving only about {v_tf_kmh} km/h. The tower survives the launch because the rocket climbs away from it and the flame trench turns the exhaust sideways.',
  'edu.hotspot.chopsticks.short': 'Chopsticks',
  'edu.hotspot.chopsticks.title': 'The chopstick arms',
  'edu.hotspot.chopsticks.body': 'Two steel arms ride on a carriage that in the photo is about {carriage_h} m up the tower. Each arm is about {arm} m long and they reach about {reach} m from the tower face. They lift boosters and ships onto the mount and, on return flights, close around the booster to catch it by its pins. Here they are parked wide open, about {span} m tip to tip, so the rocket passes cleanly. The hanging boom at about {boom_h} m is probably a service arm.',
  'edu.hotspot.olm.short': 'Launch mount',
  'edu.hotspot.olm.title': 'The orbital launch mount',
  'edu.hotspot.olm.body': 'The rocket stood on a raised, water-cooled steel deck about {olm_h} m above the ground, with a round opening under the engines and twenty hold-down clamps. Pad 2 was designed after the first Starship launch blasted concrete over kilometres. Water is released from several points, and pumps collect it for reuse; a July 2026 test reportedly flowed {flow_gpm} US gallons per minute. The deck is about {olm_w} m square. Because it is {olm_h} m up, the engine plane started {olm_h} m above the ground.',
  'edu.hotspot.trench.short': 'Flame trench',
  'edu.hotspot.trench.title': 'The flame trench',
  'edu.hotspot.trench.body': 'Under the mount a concrete trench, lined with stainless steel and cooled by water, catches the exhaust. It is estimated at {tr_l} m long, {tr_w} m wide and {tr_d} m deep, running east to west, and its diverter splits the jet into two streams. That is why the two huge clouds in the photo billow left and right of the tower. Without it the exhaust would hit flat ground, dig a crater and throw debris for kilometres, as happened on the first flight.',
  'edu.hotspot.tankfarm.short': 'Tank farm',
  'edu.hotspot.tankfarm.title': 'The tank farm',
  'edu.hotspot.tankfarm.body': 'A few hundred metres east of the pad, at its nearest about {tank_dist} m away, stands the tank farm that feeds the rocket. It has {lox_n} horizontal tanks for liquid oxygen and nitrogen, each {lox_d} m wide and {lox_l} m long, {ch4_n} for liquid methane, {water_n} water tanks for the deluge and {vap_n} vaporisers. Loading about {m0} tonnes of cold propellant takes most of an hour before launch. In the photo view it is hidden behind the steam.',
  'edu.hotspot.plume.short': 'Plume',
  'edu.hotspot.plume.title': 'The exhaust plume',
  'edu.hotspot.plume.body': 'Behind each engine the gas moves at about {ve_km} km/s, roughly ten times the speed of sound in air, and the merged plume here is about {rise_tf} m long. Methane burns almost without soot, so the core glows a pale violet-pink instead of sooty orange, like a fluorescent tube against the pad. Its temperature at the nozzle exit is still about {t_exit} K after expanding from about {t_chamber} K in the chamber.',
  'edu.hotspot.machdiamonds.short': 'Mach diamonds',
  'edu.hotspot.machdiamonds.title': 'Mach diamonds',
  'edu.hotspot.machdiamonds.body': 'The jet leaves each nozzle at a different pressure from the air around it. Near sea level the Raptor exit pressure is about {exit_p} bar against 1.01 bar outside, so the jet is slightly overexpanded. Oblique shock waves form, bounce off the plume boundary as expansion fans, and repeat. Each repeat is a bright cell, called a Mach or shock diamond, where the gas is compressed and hotter. The cells stretch and fade as the rocket climbs and the outside pressure drops.',
  'edu.hotspot.steam.short': 'Steam clouds',
  'edu.hotspot.steam.title': 'The steam clouds',
  'edu.hotspot.steam.body': 'Most of the giant clouds are water, not smoke. The pad can spray up to about {water_gal} US gallons ({water_ml} million litres) onto the mount and the trench, and over {vap_pct} % of it flashes to steam that condenses into droplets in the cool humid air. The exhaust itself adds far less: about {h2o_tps} tonnes of water and {co2_tps} tonnes of carbon dioxide per second. The orange is low morning sun, at only {sun_alt}° above the horizon, plus glow from the plume.',
  'edu.hotspot.fireball.short': 'Fireball',
  'edu.hotspot.fireball.title': 'The fireball at the base',
  'edu.hotspot.fireball.body': 'Where the plume hits the deck and trench it turns sideways and spreads. The exhaust is fuel-rich, with a mixture ratio of {of} against a perfect 4.0, so leftover carbon monoxide and hydrogen meet the air and burn again. This afterburning is what makes the bright yellow-orange glare at the foot of the column, hotter and more luminous than the pale plume above it. It is lit from inside, and it lights the steam around it.',
  'edu.hotspot.soundfront.short': 'Sound front',
  'edu.hotspot.soundfront.title': 'The sound front',
  'edu.hotspot.soundfront.body': 'Sound travels at only about {c} m/s in warm air. The engines ignite {lead} s before release, so the sound of ignition has been spreading for {lead} s plus {tf} s and is now a sphere about {r_tf_km} km in radius. Inside it the noise is overwhelming: about {spl100} dB at 100 m by a simple estimate, near {near_db} dB close to the plume. Measured on an earlier flight, it was about {spl10k} dB at 10 km and {spl20k} dB at 20 km. You would see the rocket well before you heard it.',

  // ── explainers ───────────────────────────────────────────────────────────────────────────
  'edu.ex.intro': 'Short explanations of the physics in this frame. The numbers update from the spec.',
  'edu.ex.tw.title': 'Why a thrust-to-weight of 1.5 makes a slow start',
  'edu.ex.tw.body': 'At release the rocket weighs about {w0} MN (mass × gravity) and the engines push with {thrust} MN. Only the difference accelerates it: a = g × (T/W − 1) = 9.8 × ({tw0} − 1) = {a0} m/s², about {g_net0} g.\n\nA passenger would feel {g0_load} g, because the seat pushes back with the whole thrust. Distance grows as ½ a t², so {rise_tf} m takes about {tf} s, and the speed is only {v_tf} m/s ({v_tf_kmh} km/h). The rocket gets lighter by {mdot} tonnes every second, so the acceleration keeps growing.',
  'edu.ex.tw.cap': 'Forces at release, with the ground pressing back until liftoff.',
  'edu.ex.tw.slider': 'Liftoff mass',
  'edu.ex.tw.result': 'With {m} t the engine plane reaches the frozen height at T+{tf} s, at {v} m/s, with T/W {tw} at release.',
  'edu.ex.isp.title': 'Thrust from momentum, and what Isp means',
  'edu.ex.isp.body': 'A rocket pushes because it throws mass backwards. Thrust F = ṁ × vₑ + (pₑ − pₐ) × Aₑ. With {mdot} tonnes per second leaving at {ve} m/s that is {thrust} MN. Specific impulse, Isp = vₑ / g₀ = {isp} s, is the same idea as a fuel economy figure: seconds of thrust per unit weight of propellant.\n\nThe pressure term is tiny here. At {alt_tf} m thrust has risen only {gain150} %. In vacuum it would gain 5.5 %, to about {thrust_vac} MN.',
  'edu.ex.isp.cap': 'Mass flow times exhaust velocity is thrust.',
  'edu.ex.rocketeq.title': 'The rocket equation',
  'edu.ex.rocketeq.body': 'Tsiolkovsky\'s equation says the speed a rocket gains is Δv = vₑ × ln(m₀ / m₁). With vₑ = {ve_km} km/s, a start mass of {m0} t and about {m_meco} t left when the booster stops (mass ratio {mass_ratio}), the ideal Δv is {dv_ideal} km/s.\n\nGravity and drag take a large share, so the real speed at staging is only about {dv_meco} km/s (an estimate). That is why rockets are staged: throwing away the empty booster stops you carrying its dry mass all the way to orbit.',
  'edu.ex.rocketeq.cap': 'Mass ratio decides how much speed the propellant can buy.',
  'edu.ex.steam.title': 'Why the clouds are white and orange-lit',
  'edu.ex.steam.body': 'Turning {water_t} tonnes of water into steam takes about {vap_tj} TJ, which the plume\'s {chem_gw} GW of chemical power supplies in only {vap_s} seconds. The steam meets cool humid air and condenses into droplets a few micrometres wide. Droplets that size scatter every colour about equally (Mie scattering), so the cloud looks white. It is not smoke.\n\nAbout {sun_alt}° above the horizon, the sun shines through a thick layer of air that removes blue. The clouds catch that orange light, and the plume adds its own glow from below.',
  'edu.ex.steam.cap': 'Mie scattering from micrometre droplets is nearly colour-blind.',
  'edu.ex.diamonds.title': 'Overexpanded nozzles and Mach diamonds',
  'edu.ex.diamonds.body': 'Whether a jet is over- or underexpanded depends on its exit pressure against the outside air. Here the exit pressure is about {exit_p} bar and the air is 1.01 bar, so the jet is squeezed by oblique shocks, overshoots, and expands again. Each squeeze and release makes one bright cell.\n\nAs the rocket rises the outside pressure falls, the jet becomes underexpanded, and the cells grow longer and fade. In the merged 33-engine plume near the mount the individual diamonds blur into bright streaks.',
  'edu.ex.diamonds.cap': 'Shocks and expansions repeat along the jet.',
  'edu.ex.colour.title': 'Plume colour and afterburning',
  'edu.ex.colour.body': 'The engines run fuel-rich (oxygen to fuel {of} against 4.0 for perfect burning), and methane makes no soot. So the core is only weakly luminous, with a violet-pink tint from excited OH and CO molecules and the bright Mach cells.\n\nWhere the leftover carbon monoxide and hydrogen mix with air they burn again. This afterburning heats the gas, and hot water vapour and carbon dioxide glow yellow-orange. The ground glare at the base of the column is that afterburning fire, plus steam lit from inside.',
  'edu.ex.colour.cap': 'Core: pale violet. Mixing zone: yellow-orange.',
  'edu.ex.sound.title': 'The sound front',
  'edu.ex.sound.body': 'Sound emitted at time t reaches distance r at time t + r/c. The engines lit {lead} s before release, so the front of the ignition sound has radius c × (t + {lead} s) = {c} m/s × ({tf} + {lead}) s = {r_tf_km} km.\n\nThe source is about {lw} dB of sound power, which is {eff_pct} % of the {jet_gw} GW jet. Simple spreading predicts {spl_free10k} dB at 10 km, but measurement on an earlier flight found {spl10k} dB, because air absorbs sound and terrain blocks it. The diagram shows both curves.',
  'edu.ex.sound.cap': 'Loudness against distance, model and measurement.',
  'edu.ex.staging.title': 'Max-Q and hot staging',
  'edu.ex.staging.body': 'Dynamic pressure, q = ½ ρ v², is the air load on the rocket. It rises with speed, then falls as the air thins, so it peaks around T+{t_maxq} s on this flight (the model reaches about {maxq_kpa} kPa). The engines throttle down through that peak to keep the loads down.\n\nThe booster shuts down at T+{t_meco} s, the ship lights while still attached, and they separate at T+{t_stage} s: hot staging.',
  'edu.ex.staging.cap': 'Events of the first {t_stage} seconds.',
  'edu.ex.catch.title': 'The tower catch',
  'edu.ex.catch.body': 'Instead of landing on legs, the booster comes back to the tower and the chopstick arms close around it, holding it by {pins} catch pins near the top, at about {pin_h} m up. With no legs to carry, the booster is lighter, and it can be lifted straight back onto the mount for another flight.\n\nA catch needs precision to a fraction of a metre. On Flight 14 the booster made a controlled landing burn into the Gulf instead, and no ship has been caught yet.',
  'edu.ex.catch.cap': 'Pins on the booster, arms on the tower.',
  'edu.ex.frost.title': 'Why the rocket is frosted',
  'edu.ex.frost.body': 'Liquid oxygen boils at about −183 °C and liquid methane at about −162 °C. The steel tank wall is almost as cold, so water vapour in the humid Gulf air freezes onto it. The boundary between the frosty oxygen tank and the thinner methane tank is at about {frost_h} m in the photo.\n\nFrost is a useful clue: it shows where the cold liquid sits. It also cracks and flakes off as the rocket vibrates and speeds up.',
  'edu.ex.frost.cap': 'Humid air freezes on the cold tank wall.',
  'edu.ex.heat.title': 'Radiant heat',
  'edu.ex.heat.body': 'The plume glows, so it radiates heat as well as noise. Rough estimates give about {q100} kW/m² at 100 m, enough to ignite paper, and only {q1k} kW/m² at 1 km, less than sunlight (about 1 kW/m²). The flux falls with the square of distance.\n\nThe energy comes from about {chem_gw} GW of chemical power, roughly a hundred large power stations. This is why the area is cleared for kilometres, while distant viewers feel only a brief glow.',
  'edu.ex.heat.cap': 'Inverse-square fall-off of radiant heat.',
  'edu.ex.fuel.title': 'Methane and oxygen',
  'edu.ex.fuel.body': 'Raptor burns liquid methane with liquid oxygen at a mass ratio of {of} to 1, which is fuel-rich compared with the perfect 4.0. Methane is cheap, burns clean and can be made on Mars from carbon dioxide and water.\n\nAbout {mdot_lox} tonnes of oxygen and {mdot_ch4} tonnes of methane leave every second, so {prop_b} tonnes would last about {burn_s} seconds at full thrust. The real engine cut-off is at T+{t_meco} s, because the booster keeps a reserve for landing.',
  'edu.ex.fuel.cap': 'Mass flow of oxygen and methane.',
  'edu.dia.weight': 'Weight',
  'edu.dia.thrust': 'Thrust',
  'edu.dia.net': 'Net',
  'edu.dia.ground': 'ground',
  'edu.dia.nozzle': 'nozzle',
  'edu.dia.shock': 'shock',
  'edu.dia.expansion': 'expansion',
  'edu.dia.core': 'core',
  'edu.dia.mix': 'mixing zone',
  'edu.dia.pad': 'pad',
  'edu.dia.ignition': 'ignition',
  'edu.dia.now': 'now',
  'edu.dia.free': 'free-field model',
  'edu.dia.measured': 'measured',
  'edu.dia.booster': 'booster',
  'edu.dia.ship': 'ship',
  'edu.dia.arm': 'arm',
  'edu.dia.pin': 'pin',
  'edu.dia.lox': 'liquid oxygen',
  'edu.dia.ch4': 'methane',
  'edu.dia.frost': 'frost',
  'edu.dia.km': 'km',
  'edu.dia.steam': 'steam',
  'edu.dia.droplets': 'droplets',
  'edu.dia.sun': 'low sun',
  'edu.dia.maxq': 'max-Q',
  'edu.dia.meco': 'MECO',
  'edu.dia.stage': 'staging',
  'edu.dia.heat': 'heat flux',
  'edu.dia.sunlevel': 'sunlight',
  'edu.dia.oxygen': 'oxygen',
  'edu.dia.methane': 'methane',
  'edu.dia.burn': 'burn',
  'edu.dia.thrustlabel': 'thrust',

  // ── spec key labels ──────────────────────────────────────────────────────────────────────
  'edu.k.booster_height_m': 'Booster height', 'edu.k.stack_height_m': 'Stack height', 'edu.k.ship_height_m': 'Ship height',
  'edu.k.diameter_m': 'Diameter', 'edu.k.booster_engines': 'Booster engines', 'edu.k.ship_engines': 'Ship engines',
  'edu.k.booster_prop_mass_b3_t': 'Booster propellant', 'edu.k.ship_prop_mass_b3_t': 'Ship propellant',
  'edu.k.booster_dry_mass_b3_t': 'Booster dry mass', 'edu.k.ship_dry_mass_b3_t': 'Ship dry mass', 'edu.k.payload_mass_f14_t': 'Payload',
  'edu.k.liftoff_mass_used_t': 'Liftoff mass', 'edu.k.liftoff_mass_published_t': 'Liftoff mass, published', 'edu.k.liftoff_mass_sum_of_parts_t': 'Liftoff mass, sum of parts',
  'edu.k.liftoff_thrust_b3_MN': 'Liftoff thrust', 'edu.k.liftoff_thrust_b3_Mlbf': 'Liftoff thrust (imperial)',
  'edu.k.liftoff_tw_central': 'Thrust / weight at release', 'edu.k.liftoff_tw_range_low': 'Thrust / weight, low', 'edu.k.liftoff_tw_range_high': 'Thrust / weight, high',
  'edu.k.raptor3_thrust_sl_tf': 'Raptor 3 thrust, sea level', 'edu.k.raptor3_thrust_sl_alt_tf': 'Raptor 3 thrust, press figure',
  'edu.k.raptor3_chamber_pressure_bar': 'Chamber pressure', 'edu.k.raptor3_chamber_pressure_alt_bar': 'Chamber pressure, alternative',
  'edu.k.raptor3_engine_mass_kg': 'Engine mass', 'edu.k.raptor_of_ratio': 'Oxygen to fuel ratio',
  'edu.k.raptor3_isp_sl_used_s': 'Specific impulse, sea level', 'edu.k.raptor3_isp_vac_s': 'Specific impulse, vacuum',
  'edu.k.raptor_exhaust_velocity_sl_mps': 'Exhaust velocity', 'edu.k.raptor_chamber_temperature_K': 'Chamber temperature',
  'edu.k.raptor_exit_static_temperature_K': 'Nozzle exit temperature', 'edu.k.raptor_exit_pressure_bar': 'Nozzle exit pressure',
  'edu.k.raptor_exit_mach': 'Exit Mach number', 'edu.k.raptor_nozzle_exit_diameter_m': 'Nozzle exit diameter',
  'edu.k.raptor_nozzle_expansion_ratio': 'Nozzle expansion ratio',
  'edu.k.mdot_booster_total_kgps': 'Propellant flow, booster', 'edu.k.mdot_lox_total_kgps': 'Oxygen flow', 'edu.k.mdot_ch4_total_kgps': 'Methane flow',
  'edu.k.booster_full_thrust_burn_time_s': 'Full-thrust burn time', 'edu.k.jet_mechanical_power_GW': 'Jet power', 'edu.k.chemical_power_GW': 'Chemical power',
  'edu.k.vac_thrust_booster_MN': 'Vacuum thrust', 'edu.k.thrust_gain_150m_pct': 'Thrust gain at 150 m', 'edu.k.engine_start_lead_s': 'Ignition before release',
  'edu.k.tower_height_used_m': 'Tower height', 'edu.k.olm_height_m': 'Launch mount height', 'edu.k.base_rise_to_tower_top_m': 'Rise to the tower top',
  'edu.k.t_base_at_tower_top_s': 'Time to tower top', 'edu.k.v_base_at_tower_top_mps': 'Speed at the tower top', 'edu.k.a_net_at_tower_top_mps2': 'Net acceleration there',
  'edu.k.max_q_time_f14_s': 'Max-Q time', 'edu.k.max_q_model_kPa': 'Max-Q, model', 'edu.k.meco_time_f14_s': 'Booster engine cut-off',
  'edu.k.hot_staging_time_f14_s': 'Hot staging', 'edu.k.meco_alt_est_km': 'Altitude at cut-off', 'edu.k.meco_speed_est_mps': 'Speed at cut-off',
  'edu.k.deluge_water_pad1_gal': 'Deluge water (Pad 1)', 'edu.k.deluge_water_pad1_kg': 'Deluge water mass', 'edu.k.deluge_vaporised_fraction': 'Turned to steam',
  'edu.k.deluge_pad2_test_flow_gpm': 'Pad 2 test flow', 'edu.k.deluge_pad2_test_flow_m3ps': 'Pad 2 test flow',
  'edu.k.deluge_vaporisation_energy_J': 'Energy to vaporise the water', 'edu.k.combustion_h2o_tps': 'Water from combustion', 'edu.k.combustion_co2_tps': 'Carbon dioxide from combustion',
  'edu.k.launch_table_mass_pad1_t': 'Launch table mass (Pad 1)',
  'edu.k.sound_speed_25C_mps': 'Speed of sound, 25 °C', 'edu.k.sound_front_radius_at_photo_m': 'Sound-front radius, estimate', 'edu.k.acoustic_eff_central': 'Acoustic efficiency',
  'edu.k.sound_power_level_dB': 'Sound power level', 'edu.k.spl_100m_dB': 'Loudness at 100 m', 'edu.k.spl_1km_dB': 'Loudness at 1 km',
  'edu.k.spl_10km_measured_dB': 'Loudness at 10 km, measured', 'edu.k.spl_20km_measured_dB': 'Loudness at 20 km, measured',
  'edu.k.near_field_dB': 'Near-field loudness', 'edu.k.faa_lmax_contour_dB': 'FAA noise contour',
  'edu.k.plume_radiant_flux_100m_kWm2': 'Radiant heat at 100 m', 'edu.k.plume_radiant_flux_1km_kWm2': 'Radiant heat at 1 km',
  'edu.k.vehicle.ship.tile.count_windward': 'Tiles on the windward side', 'edu.k.vehicle.ship.tile.hex_size': 'Tile width', 'edu.k.vehicle.ship.tile.gap': 'Tile gap',
  'edu.k.vehicle.booster.grid_fin.count': 'Grid fins', 'edu.k.vehicle.booster.grid_fin.scale_vs_v2': 'Grid fin size vs V2', 'edu.k.vehicle.booster.grid_fin.span': 'Grid fin span',
  'edu.k.vehicle.booster.hot_stage_vent_count': 'Hot-stage vents', 'edu.k.vehicle.booster.catch_pin_count': 'Catch pins', 'edu.k.vehicle.booster.catch_pin_height': 'Catch pin height',
  'edu.k.vehicle.photo.frost_boundary_height': 'Frost boundary height', 'edu.k.vehicle.booster.frost.lox_tank_fraction_of_height': 'Frosted share of the booster',
  'edu.k.vehicle.booster.common_dome_height': 'Common dome height', 'edu.k.vehicle.ship.aft_flap.count': 'Aft flaps', 'edu.k.vehicle.ship.forward_flap.count': 'Forward flaps',
  'edu.k.pad.tower2_height': 'Tower height', 'edu.k.pad.chopstick_carriage_height_in_photo': 'Carriage height in the photo', 'edu.k.pad.chopstick_open_span_photo': 'Arms open, tip to tip',
  'edu.k.pad.chopstick_arm_length': 'Arm length', 'edu.k.pad.chopstick_reach_from_tower_face': 'Reach from the tower', 'edu.k.pad.qd_arm_boom_height_in_photo': 'Boom height',
  'edu.k.pad.vaporizers': 'Vaporisers', 'edu.k.pad.coast_distance_east': 'Distance to the coast',
  'edu.k.scene.t_freeze': 'Frozen instant', 'edu.k.scene.vehicle_base_height': 'Engine-plane height', 'edu.k.scene.olm_deck_height': 'Launch mount deck', 'edu.k.scene.sun_altitude': 'Sun altitude',
};
